### ISSUE TITLE
请问，进行绘制图像时，提示内存不够该怎么解决

### ISSUE THREAD

**Issue by ginkgotyranny** [nju-lug/NJUThesis#114]
在原模版的基础上添加了：
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
绘图代码为：
        \begin{figure}[!h]
		\centering\begin{tikzpicture}[scale=1.3]
			\begin{axis}[xmin=1.5, xmax=2, xlabel={$\gamma$}, ylabel={Optimal function values of SDP}]
				\addplot[mark=, blue] table[x=gamma,y=p]{result.txt};
			\end{axis}
		\end{tikzpicture}
		\caption{对偶步长 $\gamma \in [1.5,2]$时\eqref{sdp}的最优函数值}
		\label{fig}
	\end{figure}
result.txt这个文件中的点对有500个，也就是要画500个点，编译之后：
![image](https://user-images.githubusercontent.com/77227575/160958935-bf8c0761-4423-421b-912a-226ed48dcf4e.png)
想请问以下该怎么解决，谢谢

**Comment by atxy-blip** [comment]
一般这种情况是出现死循环。

由于没有数据做测试，我建议你单独开一个文档测试这张图：

```TeX
\documentclass{ctexart}
\usepackage{caption}
\usepackage{unicode-math}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}

\begin{document}
\begin{figure}[!h]
\centering\begin{tikzpicture}[scale=1.3]
\begin{axis}[xmin=1.5, xmax=2, xlabel={$\gamma$}, ylabel={Optimal function values of SDP}]
\addplot[mark=, blue] table[x=gamma,y=p]{result.txt};
\end{axis}
\end{tikzpicture}
\caption{对偶步长 $\gamma \in [1.5,2]$时\eqref{sdp}的最优函数值}
\label{fig}
\end{figure}
\end{document}
```

如果这个简单的测试没问题，由于图片基本不做改动，你完全可以把这个单独生成的 pdf 作为插图插入文章。

**Comment by ginkgotyranny** [comment]
好的谢谢，也可以通过一下方法进行解决：
https://florian-rappl.de/Articles/Page/239/latex-memory#:~:text=TeX%20capacity%20exceeded%2C%20sorry%20%5Bmain%20memory%20size%3D3000000%5D.%20Fortunately,the%20file%2C%20save%20it%20and%20quit%20the%20editor.
