### ISSUE TITLE
[Feature]: 增加简历与科研成果页

### ISSUE THREAD

**Issue by ClaraLiu410** [nju-lug/NJUThesis#115]
### 先决条件

- [x] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

往年的计算机学院研究生毕业论文，在致谢页之前还有一页：简历与科研成果，但是当前模板里不存在这一页。

### 提出可能的解决方案

期待的效果：
目录：
<img width="624" alt="截屏2022-03-31 下午5 22 08" src="https://user-images.githubusercontent.com/73687540/161022501-51a6d965-bc22-43d3-9263-1bbfb95feaaa.png">

页面内容：该页包括基本信息，教育背景，学术成果等等
<img width="604" alt="截屏2022-03-31 下午5 24 51" src="https://user-images.githubusercontent.com/73687540/161023046-a4813fef-020a-46e7-b720-d4f65d9b8864.png">

### 提出考虑过的方案

目前想到的解决方案是在\begin{acknowledgement}之前加入\chapter*{简历与科研成果}，但带来的问题是目录中仍然无法显示出该页。

**Comment by harveechen** [comment]
结合issue搜到的结果，提供一个示例
```latex
\njuchapter{简历与科研成果}
\section*{基本信息}
\noindent xx, 男，汉族，199x 年 x 月出生，xxxx人。

\section*{教育背景}

\noindent \textbf{20xx 年 9 月 — 20xx 年 6 月}~南京大学xxx系 \hfill 硕士

\noindent \textbf{20xx 年 9 月 — 20xx 年 6 月}~xx大学xxx系 \hfill 本科

\section*{攻读硕士学位期间的发明专利}
\begin{enumerate}[label=\arabic*., labelindent=0em, leftmargin=*]
    \item xxxxx
\end{enumerate}

\section*{攻读硕士学位期间参与的科研课题}
\begin{enumerate}[label=\arabic*., labelindent=0em, leftmargin=*]
    \item xxxx
\end{enumerate}
```
