### ISSUE TITLE
[Feature]: 学位论文出版授权书

### ISSUE THREAD

**Issue by Kylin0123** [nju-lug/NJUThesis#116]
### 先决条件

- [x] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

特殊页面：《学位论文出版授权书 》缺失

### 提出可能的解决方案

请求补充该页面

### 额外信息

![Snipaste_2022-03-31_21-12-38](https://user-images.githubusercontent.com/21048175/161062960-76fbebe5-d29e-4d7f-ba49-4a4f853f22a0.png)

**Comment by atxy-blip** [comment]
都可以加，虽然说这个页面画起来可能有一丢丢麻烦…… 

其实之前有人提过这回事（<https://github.com/nju-lug/NJUThesis/discussions/95>），但我还没想好怎么搞（<https://github.com/nju-lug/NJUThesis/issues/96>）。清明节有空的话会重新写一下这个机制。

**Comment by atxy-blip** [comment]
大概画好了：

![image](https://user-images.githubusercontent.com/63113546/161474959-651d6f4f-ebbe-4678-bf3c-00c192f547da.png)

**Comment by Kylin0123** [comment]
感谢感谢~

**Comment by Yudezhi** [comment]
啥时候发布0.17，不想手动添加声明页了

**Comment by atxy-blip** [comment]
> @Yudezhi 啥时候发布0.17，不想手动添加声明页了

如果你本地安装有 TeX 发行版，可以直接运行仓库内对应操作系统的 `install-` 脚本，以提取新版本的样式文件。

[njuthesis-user-v0.17.0-pretest.zip](https://github.com/nju-lug/NJUThesis/files/8415089/njuthesis-user-v0.17.0-pretest.zip)

在发布新版之前，还要解决 <https://github.com/nju-lug/NJUThesis/issues/96> 的扫描页问题，再补补文档。预计是下周末。

**Comment by Yudezhi** [comment]
> > @Yudezhi 啥时候发布0.17，不想手动添加声明页了
> 
> 如果你本地安装有 TeX 发行版，可以直接运行仓库内对应操作系统的 `install-` 脚本，以提取新版本的样式文件。
> 
> [njuthesis-user-v0.17.0-pretest.zip](https://github.com/nju-lug/NJUThesis/files/8415089/njuthesis-user-v0.17.0-pretest.zip)
> 
> 在发布新版之前，还要解决 #96 的扫描页问题，再补补文档。预计是下周末。

已续命，感谢~

**Comment by dreistein543** [comment]
目前该页还有一个问题，会受到之前章节的影响添加页眉，例如在加上致谢之后，该页面会被添加上致谢的页眉，如下图：
<img width="764" alt="截屏2022-04-14 20 20 57" src="https://user-images.githubusercontent.com/30745407/163389357-cf85c997-9364-47c5-8d45-8710cf8c35b0.png">
图

**Comment by atxy-blip** [comment]
> 会受到之前章节的影响添加页眉

仓库内的开发版已经解决了这个问题。过几天如果没有更多 bug 出现，就当 v0.17.1 推了。
