### ISSUE TITLE
[Bug]: 参考文献的标题以$字符开头时无法正确处理

### ISSUE THREAD

**Issue by wangshiphys** [nju-lug/NJUThesis#118]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

参考文献标题以行内公式开头时能正确处理。
即${Z}_{2}$ gauge theory of electron fractionalization in strongly correlated systems能正确地显示为Z加下标2.

### 发生了什么

程序报错，无法正确编译。

### 最小工作示例

```TeX
% main.tex file
\documentclass{njuthesis}
\njusetup {
    bib = {
        resource = {ref.bib}
    }
}

\begin{document}
引用\cite{PhysRevB.62.7850}。
\printbibliography
\end{document}

% ref.bib file
@article{PhysRevB.62.7850,
  title = {$Z_2$ gauge theory of electron fractionalization in strongly correlated systems},
  author = {Senthil, T. and Fisher, Matthew P. A.},
  journal = {Phys. Rev. B},
  volume = {62},
  issue = {12},
  pages = {7850--7881},
  numpages = {0},
  year = {2000},
  month = {Sep},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevB.62.7850},
  url = {https://link.aps.org/doi/10.1103/PhysRevB.62.7850}
}
```

### njuthesis 模板版本

0.16.1

### 模板获取途径

通过 GitHub Releases 或镜像站下载

### 操作系统

Windows

### TeX 发行版

TeX Live 2021

### 编译引擎

XeLaTeX

**Comment by hushidong** [comment]
```
% !Mode:: "TeX:UTF-8"
% 用于测试beamer中使用gb7714-2015样式，是否满足GBT7714-2015要求，是否与book等文档类中一致
\documentclass{article}
\usepackage{ctex}

\usepackage[backend=biber,style=gb7714-2015]{biblatex}

\begin{filecontents}{\jobname.bib}
@ARTICLE{bernanke1989agency,
  AUTHOR = {Bernanke, Ben and Gertler, Mark},
  PUBLISHER = {JSTOR},
  DATE = {1989},
  JOURNALTITLE = {The American Economic Review},
  KEYWORDS = {bernanke1989agency},
  PAGES = {14--31},
  TITLE = {$P_a$ Agency costs, net worth, and business fluctuations},
}

@article{PhysRevB.62.7850,
  title = {$Z_2$ gauge theory of electron fractionalization in strongly correlated systems},
  author = {Senthil, T. and Fisher, Matthew P. A.},
  journal = {Phys. Rev. B},
  volume = {62},
  issue = {12},
  pages = {7850--7881},
  numpages = {0},
  year = {2000},
  month = {Sep},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevB.62.7850},
  url = {https://link.aps.org/doi/10.1103/PhysRevB.62.7850}
}
\end{filecontents}
\addbibresource{\jobname.bib}
    %

\begin{document}

\nocite{*}

\printbibliography


\end{document}

```

结果为：

![图片](https://user-images.githubusercontent.com/20421795/161374520-70fbb90e-3fcb-404c-9d12-13e2901afa0e.png)

**Comment by wangshiphys** [comment]
> 

你好，我是想向我上面所说的那样使用njuthesis模板来写论文，然后就遇到了上述问题。和你提供的这个例子好像不太一样，请问你知道我遇到的问题该怎么解决吗？

**Comment by wangshiphys** [comment]
> 

你好，我是想向我上面所说的那样使用njuthesis模板来写论文，然后就遇到了上述问题。和你提供的这个例子好像不太一样，请问你知道我遇到的问题该怎么解决吗？

**Comment by wangshiphys** [comment]
@hushidong 
你好，我是想向我上面所说的那样使用njuthesis模板来写论文，然后就遇到了上述问题。和你提供的这个例子好像不太一样，请问你知道我遇到的问题该怎么解决吗？

**Comment by atxy-blip** [comment]
@hushidong 是 `biblatex-gb7714-2015` 的开发者，他只对这个样式负责，所以给的是通用例子。

在这个模板里确实有问题，我还没头绪，但也可以先加一组花括号包起来的空白内容就当无事发生：
```
title = {{}$Z_2$ gauge theory of electron fractionalization in strongly correlated systems}
```

**Comment by hushidong** [comment]
把这个参考文献删掉，看还有没问题？上面的例子告诉你不是你认为的那个问题，所以需要查查其他可能的问题。

**Comment by atxy-blip** [comment]
我直接套用他给的条目确实会出问题……

```TeX
\documentclass{njuthesis}
\addbibresource{ref.bib}
\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by hushidong** [comment]
你换成biblatex标准样式试试看？

**Comment by hushidong** [comment]
你换成biblatex标准样式试试看？

**Comment by hushidong** [comment]
我这复现不了，查不了。你把出错的所有文档发给我看看，包括bbl，log等。

**Comment by hushidong** [comment]
可能是大小写变换导致的，先发给我看一下吧

**Comment by wangshiphys** [comment]
[test0.zip](https://github.com/nju-lug/NJUThesis/files/8403618/test0.zip)
[test1.zip](https://github.com/nju-lug/NJUThesis/files/8403619/test1.zip)
我用你给的例子进行了测试，去掉style=gb7714-2015选项后可以正常编译得到正确结果，加上这个选项就会出错。编译的命令都是latexmk -xelatex。

**Comment by atxy-blip** [comment]
我提供一个在线编辑器的例子：

<https://tex.nju.edu.cn/4336977663spwdqdqzwvvb>

**Comment by hushidong** [comment]
\BeforeBeginEnvironment{document}{\DeclareFieldFormat{titlecase}{%
    \iftoggle{bbx:titlelink}{%
        \iffieldundef{url}{#1}{\href{\thefield{url}}{#1}}}%
        {#1}}}

加个这个试试吧，估计是biblatex 把 `\MakeCapital`的逻辑改了。最近较忙，我没有跟，我想等texlive 2022出来再看一下，没想到出现这样的问题了，

你在正文测试一下：
```
\MakeUppercase {text}
\MakeUppercase {text$P_a$}
\MakeUppercase {$P_a$text}
\MakeUppercase text
\MakeUppercase text$P_a$
\MakeUppercase $P_a$text
\MakeCapital {text}
\MakeCapital {text$P_a$}
\MakeCapital {$P_a$text}
\MakeCapital text
\MakeCapital text$P_a$
\MakeCapital $P_a$text
```
里面的逻辑改了，本来应该是能正确处理了，现在存在问题了。我后面看看他改了啥。

**Comment by hushidong** [comment]
或者用这个试试：
\BeforeBeginEnvironment{document}{
\DeclareFieldFormat{titlecase}{%
    \iftoggle{bbx:titlelink}{%
        \iffieldundef{url}{\MakeCapital{#1}}{\href{\thefield{url}}{\MakeCapital{#1}}}}%
        {#1}}
}

如果这个没有错，那么就是差了一次展开，导致$被吃掉了。

**Comment by hushidong** [comment]
在 https://tex.nju.edu.cn/4336977663spwdqdqzwvvb 测了下，的确是的。后面我会更新biblatex-gb7714-2015。
原来是`\MakeCapital#1`，以后会改成 `\MakeCapital{#1}`。差了一层编组，导致原来的方式把流中$吃了。

**Comment by atxy-blip** [comment]
多谢，在 `biblatex-gb7714-2015` 更新后我会关闭 issue。

**Comment by hushidong** [comment]
已更新，ctan可能需要两天出来。
