### ISSUE TITLE
[Feature]: 目录可否选择采用完整标题

### ISSUE THREAD

**Issue by vill-jiang** [nju-lug/NJUThesis#119]
### 先决条件

- [x] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

为了避免页眉出现文字重叠的问题，我使用了模板中的短标题功能。
`\section[短标题]{这是我非常非常非常非常完整的标题}`

但也因此导致目录显示了短标题而难以表达其原有含义。
![image](https://user-images.githubusercontent.com/24198247/161419004-b6867a9e-ddf0-4c55-9e09-bc7011320148.png)

### 提出可能的解决方案

是否可采用文档选项或者其它形式使用户可选择目录使用完整标题呢？

**Comment by zepinglee** [comment]
需要修改 `\chapter`、`\section` 等命令的底层实现。

清华这边的格式允许页眉换行（<https://github.com/tuna/thuthesis/issues/735>），作为参考。

**Comment by vill-jiang** [comment]
不错的方案👍。
不过南大这边的模板中页眉是“左章右节”的方案，若采用THU的方法应需要对章和节的标题均有允许换行的实现。
![image](https://user-images.githubusercontent.com/24198247/161430317-2b607e51-8745-425c-b067-ba1a288945a6.png)

**Comment by atxy-blip** [comment]
请看 <https://tex.stackexchange.com/questions/6862/how-can-i-display-a-short-chapter-name-in-the-header-and-a-long-chapter-name-in>，用下面这两个命令即可覆盖页眉页脚的标题设置：

```TeX
\chapter[长长长长长长长长长长长长长长长长长长长长长长长长目录标题]{长长长长长长长长长长长长长长长长长长长长长长长长标题}
\chaptermark{页眉短标题}

\section[长长长长长长长长长长长长长长长长长长长长长长长长目录标题]{长长长长长长长长长长长长长长长长长长长长长长长长标题}
\sectionmark{页眉短标题}
```

------

`njuthesis` 现在对 `twoside` 模式的设置是奇数页呈现节标题，偶数页呈现章标题，所以也很好奇你目前是否用的是 `oneside` 模式，或者有没有用上最新版。新版手册中也给出了页眉内容的定制方式。

**Comment by vill-jiang** [comment]
感谢，完美解决问题。👍
另，以上内容确实是设置了 oneside 模式。
