### ISSUE TITLE
请问下编辑公式，上下行间距较大该怎么调整

### ISSUE THREAD

**Issue by ginkgotyranny** [nju-lug/NJUThesis#124]
数学系论文中参杂较多的公式，今天提交老师审查，老师认为公式与文本之间的空白过大：
![image](https://user-images.githubusercontent.com/77227575/163154023-0e64b2aa-2864-41b6-b82c-0d3f3ac0383f.png)
上图中公式与上下文之间行间距太大，想请问下该怎么调整，代码如下：
![image](https://user-images.githubusercontent.com/77227575/163154189-3172ff3e-362c-4bcc-8012-6faa4bfaf8f4.png)

**Comment by atxy-blip** [comment]
试试在 `\maketitle` 后加上 `\raggedbottom`？

**Comment by ginkgotyranny** [comment]
加上了之后，编译和之前没有变化

**Comment by atxy-blip** [comment]
那就不是自动拉伸导致的，可以试试手动削减相关公式的间距

```TeX

\begin{definition}[凸集]
\setlength{\abovedisplayskip}{-10pt}
\setlength{\abovedisplayshortskip}{-10pt}
\setlength{\belowdisplayskip}{-10pt}
\setlength{\belowdisplayshortskip}{-10pt}
集合$C$被称为凸集，如果$C$中任意两点间的线段仍在$C$中，即对于任意$x_1 x_2 \in C$
\begin{equation}
    \theta x_1 + (1-\theta) x_2 \in C
\end{equation}
\end{definition}
```

公式后部的空白是 `definition` 环境与下方文字产生的，无法用上面的命令调整。

**Comment by ginkgotyranny** [comment]
可以了，谢谢
