### ISSUE TITLE
请问下编译出的矩阵太大，该怎么修改成正常样式

### ISSUE THREAD

**Issue by ginkgotyranny** [nju-lug/NJUThesis#125]
使用如下代码构造矩阵：
![image](https://user-images.githubusercontent.com/77227575/163158537-695ffdb4-276c-4bc5-b3fc-193aa3d3f52c.png)
编译出的矩阵如下：
![image](https://user-images.githubusercontent.com/77227575/163158584-68c538ce-8654-49a6-a1db-80e2ab069ea2.png)
矩阵太大了，格式很奇怪，请问下该怎么修改，才能得到正常的格式，如下：
![image](https://user-images.githubusercontent.com/77227575/163158678-c95c18b2-c856-4634-9309-6058c2cb4b4a.png)

**Comment by ginkgotyranny** [comment]
不好意思，这个问题不是模板本身的问题，是我自己遇到编译问题的时候，在前面加了：
\renewcommand\arraystretch{2}
之后导致的

**Comment by atxy-blip** [comment]
也可以试试 [`nicematrix`](http://mirrors.ctan.org/macros/latex/contrib/nicematrix/nicematrix.pdf) 宏包。

**Comment by ginkgotyranny** [comment]
> 也可以试试 [`nicematrix`](http://mirrors.ctan.org/macros/latex/contrib/nicematrix/nicematrix.pdf) 宏包。

**Comment by ginkgotyranny** [comment]
好的谢谢
