### ISSUE TITLE
[Feature]: 增加脚注调整接口

### ISSUE THREAD

**Issue by atxy-blip** [nju-lug/NJUThesis#129]
### Discussed in https://github.com/nju-lug/NJUThesis/discussions/127

<div type='discussions-op-text'>

<sup>Originally posted by **dreistein543** April 14, 2022</sup>
1. 使用上标圆圈数字 ① 来编号
2. 每一页重新编号
3. 悬挂缩进 1 字符
</div>

### 解决方法
1. 使用 `pifont` 包，模仿 `fduthesis` 的脚注设定方式
2. 为 `footmisc` 传入 `perpage` 选项
3. 为 `footmisc` 传入 `hang` 选项

进一步细化就是使用 `nju/footnote/font` 和 `nju/footnote/option` 两个键值对来传入设置，并将 `footmisc` 挂在导言区末尾载入以吸收这些选项。

**Comment by atxy-blip** [comment]
传入 `hang` 选项暂时失败了。

**Comment by atxy-blip** [comment]
目前你可以在文档类选项中使用 `footmisc=false`，这使模板不会自动载入 `footmisc`，然后就可以手动使用 `hang` 选项载入这个宏包。

**Comment by dreistein543** [comment]
> 目前你可以在文档类选项中使用 `footmisc=false`，这使模板不会自动载入 `footmisc`，然后就可以手动使用 `hang` 选项载入这个宏包。

我尝试了一下，发现如果设置`footmisc=false` 也会同时导致 `pifont` 的圆圈数字消失，而且摸索调整悬挂缩进也比较麻烦。在知乎上找到一个 [LaTeX脚注要怎么在行内垂直居中呢？ - 李清的回答 - 知乎](https://www.zhihu.com/question/53030087/answer/136006617) 尝试了一下感觉是可以的，或许后续的修改可以作为参考。

另一位 [刘海洋的回答](https://www.zhihu.com/question/53030087/answer/136097745) 我没有尝试，不过据说可以解决使用圆圈数字每页脚注不能超过10个的限制，或许对后续的更新有启发。因为据 刘海洋 所言，李清 的实现方法似乎与 footmisc 兼容性不够好

**Comment by atxy-blip** [comment]
已更新在 dev 分支。`footnote/style = pifont`选项作废，改为 `footnote/style = circled`选项（通过 `circledtext` 包实现，这个包今年4月才发布，可能需要使用 tlmgr 手动安装。我仍在考虑是否应该保留 `pifont` 包作为兼容选项），同时新增了 `footnote/hang`选项。目前默认使用悬挂缩进。

另：之后遇到脚注问题请开新帖讨论。

<img width="462" alt="image" src="https://user-images.githubusercontent.com/63113546/196022891-25148919-e1ef-4b32-8eb1-1e82e4acef4a.png">
