### ISSUE TITLE
[Bug]: 学位论文出版授权书，双导师姓名BUG

### ISSUE THREAD

**Issue by FeynmanCheng** [nju-lug/NJUThesis#130]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

 导师姓名：张三 李四

### 发生了什么

使用最新版本cls文件，南大tex编译

学位授权页面，双导师，两个人名字中间没有空格

效果：  导师姓名：张三李四

### 最小工作示例

```TeX
supervisor = {张三,教授},
 supervisor-ii = {李四,讲师},
```

### njuthesis 模板版本

快更新吧

### 模板获取途径

通过 GitHub Releases 或镜像站下载

**Comment by FeynmanCheng** [comment]
还有个问题，此页面的页眉是致谢

**Comment by atxy-blip** [comment]
> 两个人名字中间没有空格

已修复。

> 此页面的页眉是致谢

这个在之前提交中修复了，目前仓库中的开发版本是没问题的。
