### ISSUE TITLE
一处笔误

### ISSUE THREAD

**Issue by note286** [nju-lug/NJUThesis#137]
[此处](https://github.com/nju-lug/NJUThesis/blob/8fabd93c6ae88d717a2ac25f184c6d7200e8d215/source/njuthesis.dtx#L810)将`宏包`写成了`红包`。

**Comment by atxy-blip** [comment]
感谢指正。已经改好了，下次一起提交。

笔误这种东西不妨直接 PR~

**Comment by note286** [comment]
担心commit信息啥的有特殊的规矩，又懒得去了解了，所以提issue让作者修改是最稳妥的，哈哈哈。
