### ISSUE TITLE
LuaLaTeX编译不能生成正确的pdf书签

### ISSUE THREAD

**Issue by atxy-blip** [nju-lug/NJUThesis#14]
下载 Github Actions 用 LuaLaTeX编译的pdf发现，目录、中英文摘要，以及目录中的章节名称均不能正确跳转，而 XeLaTeX 生成的pdf结果正确。

**Comment by myandeg** [comment]
查看了commit https://github.com/nju-lug/NJUThesisUndergraduate/commit/1e3b0943534c8c38e63f26bcd6d371e7b41a17a6 和 https://github.com/nju-lug/NJUThesisUndergraduate/commit/9963e7338063f73aeb77101dd9d1a7d0604b106c 通过github actions用lualatex编译得到的pdf

使用okular书签和目录跳转均正常
使用firefox浏览器也正常
使用chrome浏览器时章节无法跳转
使用zathura时摘要和章节无法跳转

**Comment by FengChendian** [comment]
懂了，开源万岁

**Comment by myandeg** [comment]
> 懂了，开源万岁

但是zathura也是开源的

**Comment by FengChendian** [comment]
> > 懂了，开源万岁
> 
> 但是zathura也是开源的

那FF万岁🤡

**Comment by atxy-blip** [comment]
已修复，原因是使用了中文的标签名称。

我是傻逼。
