### ISSUE TITLE
[Feature]: 硕士研究生封面与研究生院官网不一致

### ISSUE THREAD

**Issue by iYuqinL** [nju-lug/NJUThesis#144]
### 先决条件

- [x] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

硕士研究生的论文封面与研究生院提供的封面模板不一致。主要表现为：
1. 校徽和校名研究生院模板是彩色的，本模板是黑白的。这个比较容易改，更换nju-emblem和nju-name即可。
2. 封面的 “专业方向” 与研究生院模板不同，研究生院模板对于学术型硕士是 “专业名称”，专业型硕士是 “专业学位类别(领域)”。 这个我在 .def 文件找到了对应的定义，但是直接修改，由于“专业学位类别(领域)”过长，会出现超出范围的情况。
3. 封面的 “论文题目”，“作者姓名”，“专业名称”等，在研究生院模板上感觉是黑体(虽然我觉得不好看)。
4. 封面 “南京大学” 下来的“研究生毕业论文” 的字间距比研究生院模板的小，字体看起来也没有那么粗(小细节应该不影响？)

### 提出可能的解决方案

对于 1.，可以直接个人更换nju-emblem和nju-name即可，或者模板这边也提供彩色的的nju-emblem和nju-name，让用户通过已有的 style/emblem-img 选项选择。
对于2.，对模板进行相应的文字定义调整，专业硕士的过长可能还涉及对应的字体缩小的调整。
对于3.，是否可以增加一个封面的这些 item 的字体的选项？

### 额外信息

研究生封面模板截图对比如下
1. 本论文模板在修改了校徽颜色之后
![4005fcc9ee45f25c2912a7941586635](https://user-images.githubusercontent.com/25427848/167561609-4b917c19-a79d-40ce-a671-c113edb7bf1d.png)
2. 研究生院学术硕士封面模板
![40e69d01c275320bf17241a9b9a5258](https://user-images.githubusercontent.com/25427848/167561785-4c4bf7b2-2a93-4a68-8e54-426ba8dc700f.png)
3. 研究生院专业硕士封面模板
![ababa1fa97967211df1bad59fab1f27](https://user-images.githubusercontent.com/25427848/167561885-b00e42d1-f51b-4573-b49a-27147f39bc3f.png)

**Comment by atxy-blip** [comment]
很感谢您的建议，但在着手进行修改前，我想先谈谈*排版*本身的问题。

在各种意义上，MS Word 只是一个文字处理软件，而非排版软件。所见即所得的形式在让我们简单实现页面内容的同时，也遮蔽了一个要点，那就是排版要求将特定元素精确摆放在特定位置上。Word 无法保证成稿效果的一致性。而在学校发放的公告和提供的 `.docx` 文件中，我们并没有看到“校徽应该保持什么尺寸”、“封面上的若干行信息之间的行距是多少” 这样的硬性指标。本模板前后参考了若干份空白模板和已通过的毕业论文，其封面样式差异之大令人震惊。

所以很容易得到这样一个结论：如果我们不与研究生院对接出一个精细到磅（pt）的设计规范，否则论文封面上只要依次出现给出的要素就好，完全不必纠结细节。当然，我也在烦神我的文章，近期无暇出面交涉。

至于封面上文字的问题，也是因为规范不确定。这点模板预留了接口
```TeX
\njusetname{field}{专业学位类别（领域）}
\njusetlength{coverlabel}{160pt}
```

**Comment by atxy-blip** [comment]
仔细考虑了一下，决定暑假更新大版本时完全模仿 Word 文件重做封面。

**Comment by dreistein543** [comment]
说起来看到 说明文档里曾经说明过可以使用 `njuvisual` 包来绘制彩色的校徽和校名，不知道是不是可以考虑直接在配置文档中进行设置

**Comment by atxy-blip** [comment]
校徽直接绘制是没问题的，模板中的用法稍微有点 tricky，一旦载入外置图片就不能改颜色。

一种很显然的解决方法是生成独立的彩色校徽。因为调用 `njuvisual` 后每次编译时都要重新绘制一遍，内置校徽在耗时上不好看。
```tex
\documentclass{standalone}
\usepackage{njuvisual}
\begin{document}
\njuemblem[color=njuviolet]{!}{!}
\end{document}
```

当然，内置的 `\njuemblem` 命令参数可以加。改天加一个 `\njusetformat` 条目吧。

**Comment by atxy-blip** [comment]
已随 v1.0.0 发布。

**Comment by imba-tjd** [comment]
@atxy-blip  请问彩色logo的设置还有效吗？我在`njuthesis-setup.def`的最后一行加了楼上两句njusetformat，编译后还是黑白的
