### ISSUE TITLE
请问英文摘要页中的标题如何指定换行位置？

### ISSUE THREAD

**Issue by ginkgotyranny** [nju-lug/NJUThesis#149]
英文标题换行的位置刚好处于其中一个单词的中间，将一个单词分为了两段
![image](https://user-images.githubusercontent.com/77227575/169199635-d40c8ca5-b422-467d-8769-a438ce3b8edf.png)
因此我想从Direction这个单词开始换行，在Direction前用 \\ 指定换行还是无法成功
![image](https://user-images.githubusercontent.com/77227575/169199838-c5e9e0dd-1c06-4163-8995-fe19c909a501.png)
![image](https://user-images.githubusercontent.com/77227575/169199861-f9cad5bf-da67-4a11-a4e3-5be4fe43a75a.png)
想请问该如何修改

**Comment by atxy-blip** [comment]
这个问题已经在 v0.17 解决了。建议更新模板版本。

摘要中的标题在设计之初就是无法手动换行的，论文标题的换行位置优先保证在封面页生效。
