### ISSUE TITLE
[Feature]: 在 author-year 文献样式下显示序号

### ISSUE THREAD

**Issue by liuzike** [nju-lug/NJUThesis#151]
### 先决条件

- [ ] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

使用 author-year的模式参考文献列表时可以 显示 序号吗，并调整左对齐

### 提出可能的解决方案

修改 gb文件？

**Comment by atxy-blip** [comment]
见 `biblatex-gb7714-2015` 宏包手册，添加 `gbalign = right` 选项即可。示例如下：

```tex
\documentclass{njuthesis}

\begin{filecontents}{ref.bib}
@article{baiardi2019,
  title = {Large-{{Scale Quantum Dynamics}} with {{Matrix Product States}}},
  author = {Baiardi, Alberto and Reiher, Markus},
  author+an = {2=thesisauthor},
  date = {2019-06-11},
  journaltitle = {J. Chem. Theory Comput.},
  volume = {15},
  number = {6},
  pages = {3481--3498},
  issn = {1549-9618, 1549-9626},
  doi = {10.1021/acs.jctc.9b00301},
  langid = {english}
}
\end{filecontents}

\njusetup{
    bib = {
        style = author-year,
        resource = {ref.bib},
        option = {
            gbalign = right
        }
    }
}

\begin{document}

\nocite{*}
\printbibliography

\end{document}

```

![image](https://user-images.githubusercontent.com/63113546/170206601-5e767a1b-f875-4b7a-9a98-d63e4ea3b0a4.png)

**Comment by dreistein543** [comment]
注意 gbalign=right 意味着数字是“右对齐”的（即对齐到右中括号]，数字在中括号中是不等宽的（1比10要窄））
不太清楚你的左对齐是什么意思，gbalign = left / right / center 都可以考虑，具体情况可以 texdoc biblatex-gb7714-2015 查看 gbalign 的示例，确定自己需要的模式
