### ISSUE TITLE
[Bug]: Font shape 'TU/TimesNewRoman(0)/m/sc' undefined

### ISSUE THREAD

**Issue by connglli** [nju-lug/NJUThesis#169]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

能够找到smallcaps的字体

### 发生了什么

找不到smallcaps的字体，导致
1. 编译器报warning，并用Times New Roman Regular替代
2. 博士英文封面`Doctor of Philosophy`显示异常
3. `\textsc{}`命令无法显示smallcaps字体

```
LaTeX Font Warning: Font shape `TU/TimesNewRoman(0)/m/sc' undefined
(Font)              using `TU/TimesNewRoman(0)/m/n' instead on input line 7.
```

<img width="682" alt="Screenshot 2022-11-29 at 13 30 37" src="https://user-images.githubusercontent.com/14104191/204446730-633bafff-d551-41fe-9074-c7ef49e36c17.png">

### 最小工作示例

```TeX
\documentclass[
    type = doctor
]{njuthesis}

\begin{document}

\maketitle

\begin{abstract}
    中文摘要
\end{abstract}

\begin{abstract*}
    English abstract
\end{abstract*}

\tableofcontents

\mainmatter

\chapter{引言}

\begin{acknowledgement}
    感谢 \href{https://git.nju.edu.cn/nju-lug/lug-introduction}{LUG@NJU}。
\end{acknowledgement}

\end{document}
```

### njuthesis 模板版本

master branch; dev branch; v1.1.0

### 模板获取途径

从 Git 仓库下载

### 操作系统

macOS

### TeX 发行版

TeX Live 2022

### 编译程序

XeLaTeX

### 额外信息

使用下面的代码可部分该解决问题，但这个问题不应该由用户解决，而应该由模板解决

```
\setmainfont{Times New Roman}[
  SmallCapsFont={TeX Gyre Termes},
  SmallCapsFeatures={Letters=SmallCaps},
}
```

**Comment by AlphaZTX** [comment]
提供一个解决方案：
```
\setmainfont{Times New Roman}[SmallCapsFont=Times New Roman:+smcp]
```
这样你在正文中输入的 `\textsc{Aa}` 就会是正确的样子了。

注：这里的 `+smcp` 是直接调用 OpenType features 中的 smcp，这一特性会将小写字母的 glyph 做出替换。

**Comment by AlphaZTX** [comment]
（这其实并不是一个 bug，@atxy-blip 可以改一下标签

**Comment by connglli** [comment]
@AlphaZTX 我在额外信息里就是用TeX Gyre Termes的smallcap来替代TimesNewRoman的smallcap，但这不应该由用户来处理吧，模板里就应该处理好。至少需要写在manual里告诉用户这个问题的存在以及如何解决。

**Comment by connglli** [comment]
这个问题只有macOS存在，所以上面的代码还应该check一下操作系统

**Comment by AlphaZTX** [comment]
> @AlphaZTX 我在额外信息里就是用TeX Gyre Termes的smallcap来替代TimesNewRoman的smallcap，但这不应该由用户来处理吧，模板里就应该处理好。至少需要写在manual里告诉用户这个问题的存在以及如何解决。

这个是 macOS 系统下字体的问题，我觉得可以让文档作者说明一下。

其实这个思路很简单，写起来也不难，只需要检测系统字体册下是否存在这个字体就好，如果存在，那就开启一个 fallback，如果不存在，那就用另一个设置。

但是我没有参与任何贵校模板的开发工作。这方面的建议可以跟 @atxy-blip 提一下。

**Comment by atxy-blip** [comment]
我借了一台 mac 还在做测试，本来打算等都解决了再回复的。

> 解析了一下 macOS 中的 Times New Roman

这个明明是我发给 @AlphaZTX 的 QAQ

**Comment by AlphaZTX** [comment]
> 这个是 macOS 系统下**字体**的问题（问题在字体文件本身，而非操作系统，毕竟你手动拷贝一个 Windows 下的 Times New Roman 就可以解决这个问题），但可以让文档作者说明一下。

对于这一段，我再做一点说明：Times New Roman（或 TimesNewRomanPSMT）在 Windows 和 macOS 下的区别在于版本。Windows 10 中的 Times New Roman 的版本为 `7.00`，而 macOS 下的 Times New Roman 的版本为 `5.01.3x`（以 @atxy-blip 
 提供给我的为例），这个问题似乎要跟 Apple 的人说。

**Comment by atxy-blip** [comment]
增加了对 smcp 特性的检测，如果缺失就会抛出警告信息并替换成 TG Termes。可以试一试有没有解决问题。

**Comment by connglli** [comment]
Fixed

**Comment by Tedxz** [comment]
关于该问题，MacOS配置下非衬线字体（例如章、节标题）也不支持smcp特性。我目前是通过拷贝windows版本的Arial字体解决的，应该也可以通过类似的方法在模板中自动fallback。
