### ISSUE TITLE
[Bug]: `nl-cover`导致编译卡住

### ISSUE THREAD

**Issue by connglli** [nju-lug/NJUThesis#170]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

添加`nl-cover`后应该正常编译，且生成国家图书馆封面

### 发生了什么

无法正常编译，Ctrl-C 后发现卡在`\maketitle`，见下图

<img width="578" alt="Screenshot 2022-11-29 at 13 35 42" src="https://user-images.githubusercontent.com/14104191/204447447-83f09626-fbc9-4a00-878a-61bd7fbc2680.png">

### 最小工作示例

```TeX
\documentclass[
    type = doctor,
    nl-cover = true
]{njuthesis}

\begin{document}

\maketitle

\begin{abstract}
    中文摘要
\end{abstract}

\begin{abstract*}
    English abstract
\end{abstract*}

\tableofcontents

\mainmatter

\chapter{引言}

\begin{acknowledgement}
    感谢 \href{https://git.nju.edu.cn/nju-lug/lug-introduction}{LUG@NJU}。
\end{acknowledgement}

\end{document}
```

### njuthesis 模板版本

master branch, dev branch, v1.1.0

### 模板获取途径

从 Git 仓库下载

### 操作系统

macOS

### TeX 发行版

TeX Live 2022

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
已修复。
