### ISSUE TITLE
[Bug]: 研究生模板封面上第二导师无法正确显示

### ISSUE THREAD

**Issue by moyu3585** [nju-lug/NJUThesis#172]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

论文封面需要两位导师姓名

### 发生了什么

![image](https://user-images.githubusercontent.com/39209867/206480689-6d9de432-5e4c-4afe-b941-16f62448ea60.png)
可以看到两位指导老师姓名均为第一个主导师姓名

### 最小工作示例

```TeX
模板仅使用双导师制就会出现该问题，无任何修改。
```

### njuthesis 模板版本

v1.1.0

### 模板获取途径

通过 GitHub Releases 或镜像站下载

### 操作系统

Linux

### TeX 发行版

texlive 2022

### 编译程序

XeLaTeX

### 额外信息

实测v1.0.0没有问题，v1.1.0有此问题。

**Comment by atxy-blip** [comment]
应该是修 #165 时给漏了，感谢指出：）

**Comment by moyu3585** [comment]
> 应该是修 #165 时给漏了，感谢指出：）

想请问一下这种问题一般是下个版本更新解决还是github这边近期直接pr修正

**Comment by atxy-blip** [comment]
上面引用的提交已经修好，本来也不是大问题。更新方法见手册 2.2.2 节的即时安装方法。

下一次提升版本号预计是在月底，以跟进本科生院在本学年的毕业论文通知。

**Comment by moyu3585** [comment]
我从release下载新的包上传到overleaf编写，反复试了大概三四次问题好像并没有修复，第二导师显示仍不正常。时间是凌晨一点和凌晨三点均这种情况。

**Comment by atxy-blip** [comment]
我们不应该指望12月4日上传到 Releases 的包能解决昨晚的问题……

因为你提到你在 Linux 用 TeX Live，本意是让你关注手册 2.2.2 节里面的后一段话：

> 对于希望使用*主仓库中版本*的用户，本模板也提供了扁平化安装脚本，用于释放供编译
> 的空白模板和格式文件。Windows 用户请直接双击打开 `install-win.bat`；其他平台（包括
> macOS 和 Linux）用户请在此目录下运行
> ```bash
> bash install-unix.sh
> ```
> 该脚本会生成一个 mythesis/ 目录以便从头写作，仓库内除此文件夹以外的内容都可以尽情
> 删除。

`njuthesis` 并不是每修一个 bug 就传一次 Releases。模板的本意是小 bug 不影响写作，届时换掉 `njuthesis.cls` 和 `njuthesis-*.def` 就能得到修复。急用的话就用上面这个克隆仓库提取文件的流程，我之后再改改手册表述吧。
