### ISSUE TITLE
本科生院提供的论文模板的封面校徽是居中的，但该模板封面校徽居左

### ISSUE THREAD

**Issue by Miraitowa2001** [nju-lug/NJUThesis#173]
### 先决条件

- [X] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 提出可能的解决方案

将校徽居中即可

**Comment by atxy-blip** [comment]
导言区加 `\EditInstance{nju}{u/cover/emblem-img}{align=c}`。

这个确实是历史遗留问题，压缩包里有单独的封面文件是左对齐的校徽，到2021年的新 Word 模板就成了居中。
