### ISSUE TITLE
您好，有硕博的模板嘛？

### ISSUE THREAD

**Issue by zhoujian9410** [nju-lug/NJUThesis#18]
您好，看了一下你们做的这个本科生的模板框架，感觉很优秀啊，给你们点赞，太强了。
想问一下有硕博论文的模板嘛？

**Comment by atxy-blip** [comment]
这个模板还没有提供硕博的格式，因为我们还没找到一份普适的格式指导文件。

如果能提供基本格式参考的话，我们很乐意加入新功能！

**Comment by atxy-blip** [comment]
硕博格式已成为NJUthesis的可选项，如有建议请开新帖。

本issue将被关闭。
