### ISSUE TITLE
[Bug]: 匿名模式在摘要页仍显示校名

### ISSUE THREAD

**Issue by connglli** [nju-lug/NJUThesis#181]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

同中英文封面隐藏校徽、学校一样，中文摘要页和英文摘要页也要隐藏“南京大学”/四个字

### 发生了什么

中文摘要页和英文摘要页仍然显示“南京大学”/四个字（见下图）
![cn](https://user-images.githubusercontent.com/14104191/223340740-5a2c0caf-cdbc-41c8-80ba-8631328543ac.png)
![en](https://user-images.githubusercontent.com/14104191/223340739-f957c373-e668-4ae2-8a40-df32883d6f00.png)

### 最小工作示例

```TeX
\documentclass[
    type = doctor,
    anonymous
]{njuthesis}

\begin{document}

\maketitle

\begin{abstract}
    中文摘要
\end{abstract}

\begin{abstract*}
    English abstract
\end{abstract*}

\tableofcontents

\mainmatter

\chapter{引言}

\begin{acknowledgement}
    感谢 \href{https://git.nju.edu.cn/nju-lug/lug-introduction}{LUG@NJU}。
\end{acknowledgement}

\end{document}
```

### njuthesis 模板版本

master branch

### 模板获取途径

从 Git 仓库下载

### 操作系统

Linux

### TeX 发行版

TeX Live 2022

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
修了。

**Comment by connglli** [comment]
Fixed
