### ISSUE TITLE
[Feature]: 请问大家，英文题目如何实现使用换行控制符(\\)手动指定换行位置呢

### ISSUE THREAD

**Issue by byby221b** [nju-lug/NJUThesis#199]
### 先决条件

- [X] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

目前中文题目可以实现使用换行控制符(\\)手动指定换行位置，但是在英文题目中使用换行符时会导致封面和英文摘要页的题目同时都被换行了？如何修改模板实现封面页英文题目手动换行但摘要页不变呢？

谢谢！！

### 提出可能的解决方案

如何修改模板实现封面页英文题目手动换行但摘要页不变呢？

**Comment by rayeya** [comment]
同问

**Comment by atxy-blip** [comment]
见 <https://github.com/nju-lug/NJUThesis/issues/227>
