### ISSUE TITLE
[Feature]: 南大 2023 启用新的学位封面

### ISSUE THREAD

**Issue by connglli** [nju-lug/NJUThesis#204]
### 先决条件

- [X] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

封面已经out of date了

### 提出可能的解决方案

启用新封面：[phd-cover.zip](https://github.com/nju-lug/NJUThesis/files/11332790/phd-cover.zip)

**Comment by atxy-blip** [comment]
收到，看起来改动不小，搞好了就发 v1.2。

不过我没找到来源信息，可以贴一下网址吗？

**Comment by atxy-blip** [comment]
好了，可以在 `dev` 分支试一试。打算再补补文档就发布。

**Comment by atxy-blip** [comment]
`v1.2.0` 已发布。

**Comment by connglli** [comment]
@atxy-blip 我就不提新issue了，[PR 204](https://github.com/nju-lug/NJUThesis/commit/ffc826fe1942c6cbd10517e6b775d3fe678b5966#diff-5783cf6df2d7d35c6474c1a59c023a387d07df1160d5fd1e230606d1d3391e56L4787) 修改后删掉了`g__nju_info_degree_tl`，导致国家图书馆封面的"申请学位级别"变空。
