### ISSUE TITLE
[Feature]: 允许定理环境共享编号

### ISSUE THREAD

**Issue by Undefined01** [nju-lug/NJUThesis#207]
### 先决条件

- [X] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

目前模板提供了 `\njusetup[theorem]` 定义定理环境。但是这个指令默认各个定理之间独立编号。正常而言这个问题不大，但是对于 `theorem`、`corollary`、`lemma` 等强相关的环境使用共享的编号会更为合理。

### 提出可能的解决方案

希望能够提供一个较为方便的选项设置定理使用共享的编号。

如果设计或实现较为麻烦，也可以直接暴露一个选项手动指定需要使用的counter，手动让多个环境使用同一个counter也能达到效果。现在的counter选项只能指定父计数器，而不能直接指定使用这个计数器。

**Comment by atxy-blip** [comment]
模板没有对 `\newtheorem` 的第一个可选参数做封装，这个方便做。最近事情比较多，这周末前或许能写出来吧。

<img width="422" alt="image" src="https://user-images.githubusercontent.com/63113546/236669553-ec001d13-6515-46cf-9f3a-edc02d4c953d.png">

**Comment by atxy-blip** [comment]
顺手写了，测试例如下。新版的 `cls` 文件见 [njuthesis.zip](https://github.com/nju-lug/NJUThesis/files/11414823/njuthesis.zip)。

```tex
\documentclass{njuthesis}

\njusetup[theorem]{
    share-counter = true,
    define
}

\njusetup[theorem]{
    body-font = \ttfamily,
    % share-counter = false,
    type = {
        { {exercise} {习题} },
        { {solution} {解} }
    },
    define
}

\begin{document}
\chapter{foo}
\ExplSyntaxOn
\clist_map_inline:nn
  { axiom, axiom, theorem, exercise, example, solution, exercise }
  { \begin{#1} test \end{#1} }
\ExplSyntaxOff
\end{document}
```
<img width="222" alt="image" src="https://user-images.githubusercontent.com/63113546/236673930-c7207247-d407-4e77-bdf1-07624022a617.png">

**Comment by Undefined01** [comment]
很完美，感谢！
