### ISSUE TITLE
[Feature]: 专硕封面的“专业学位类别(领域)”和中文摘要页的“专业”应当设置为不同的内容

### ISSUE THREAD

**Issue by Pavinberg** [nju-lug/NJUThesis#208]
### 先决条件

- [X] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

以计算机系专硕为例，专硕封面的“专业学位类别(领域)”应为“工程硕士（计算机技术）“，中文摘要页的”专业“应为”计算机技术“。现有模板只能设置一个 `major` 字段同时对应这两处，无法分别进行设置。

### 提出可能的解决方案

对于专硕的封面应当自动设置成“工程硕士（`major`）”。或提供两个字段供用户设置。

**Comment by atxy-blip** [comment]
`info/major` 目前可以自动补全专业型学位封面上的信息。

**Comment by liudongmiao** [comment]
@Pavinberg 在 `1.3.2` 之后，工程硕士专业调整为

```
major = {工程硕士（计算机技术）,计算机技术},
```

格式为：

```
major = {封面专业[,摘要专业]}
```

讨论请见 #232
