### ISSUE TITLE
[Bug]: 参考文献中出现了[S.l. : s.n.]

### ISSUE THREAD

**Issue by DeclK** [nju-lug/NJUThesis#212]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

参考文献中不出现[S.l. : s.n.]
我知道这好像是符合参考文献标准的，但是学院要求去除这一部分

### 发生了什么

所有的inproceedings参考文献均出现了[S.l. : s.n.]
![image](https://github.com/nju-lug/NJUThesis/assets/68807035/600f5ce1-56f2-4928-97f7-f09df6822f7b)

### 最小工作示例

```TeX
@inproceedings{girshickRichFeatureHierarchies2014,
  title = {Rich Feature Hierarchies for Accurate Object Detection and Semantic Segmentation},
  booktitle = {Proceedings of the {{IEEE}} Conference on Computer Vision and Pattern Recognition},
  author = {Girshick, Ross and Donahue, Jeff and Darrell, Trevor and Malik, Jitendra},
  year = {2014},
  pages = {580--587}
}
使用该bib就会出现上述情况
```

### njuthesis 模板版本

v1.1.2

### 模板获取途径

None

### 操作系统

None

### 编译程序

None

**Comment by DeclK** [comment]
已解决，通过将 `njuthesis.cls` 文件中的代码进行了修改
原代码
```cls
    \clist_gput_right:Nn \g__nju_blx_option_clist { backend = biber }
```
修改后
```cls
    \clist_gput_right:Nn \g__nju_blx_option_clist { backend = biber , gbpub=false}
```

**Comment by atxy-blip** [comment]
见 <https://github.com/hushidong/biblatex-gb7714-2015/issues/32>，这个字段是 feature 而不是 bug（

以及模板给了用于给 `biblatex` 传宏包参数的 `bib/option` 选项，可以不用直接改 `.cls` 文件。
