### ISSUE TITLE
[Bug]: 封面密级默认值应该是“公开”

### ISSUE THREAD

**Issue by Soulike** [nju-lug/NJUThesis#213]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

![IMG_2754](https://github.com/nju-lug/NJUThesis/assets/23612560/8830a2dd-e6af-49a5-9864-1e9e988765cf)

### 发生了什么

目前版本的默认值是“不涉密”
https://github.com/nju-lug/NJUThesis/blob/5fcd8ab82664a7363517739706783d69306cebdf/docs/njuthesis-setup.def#L97

### 最小工作示例

```TeX
见上文
```

### njuthesis 模板版本

v1.2.1

### 模板获取途径

<https://tex.nju.edu.cn>

### 操作系统

macOS

### TeX 发行版

Tex Live 2023

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
改了，通知也发了，等下传个新版到 tex.nju。关联 #86。
