### ISSUE TITLE
[Bug]: 中文封面第二导师文本超出下划线范围

### ISSUE THREAD

**Issue by YmHAHAHa** [nju-lug/NJUThesis#215]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

第二导师文本不会超出下划线范围

### 发生了什么

![image](https://github.com/nju-lug/NJUThesis/assets/42953643/d49e0e2f-1f2b-44ca-9e5b-fff9ad546fb2)

### 最小工作示例

```TeX
% njuthesis-setup.def
supervisor = {某某某,教授},
supervisor-ii = {某某某,助理研究员},
```

### njuthesis 模板版本

v1.2.1

### 模板获取途径

通过 GitHub Releases 或镜像站下载

### 操作系统

Windows

### TeX 发行版

TeX Live 2022

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
#214 请不要重复提问。
