### ISSUE TITLE
[Bug]: 英文题目太长，英文标题页行间距格式有问题；如果有第二导师，英文标题页直接变为两页了

### ISSUE THREAD

**Issue by JackokieZhao** [nju-lug/NJUThesis#217]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

![image](https://github.com/nju-lug/NJUThesis/assets/19789205/39bb676f-6329-43e1-b409-c86a3fbfe761)

### 发生了什么

英文题目太长，英文标题页行间距格式有问题；如果有第二导师，英文标题页直接变为两页了
![image](https://github.com/nju-lug/NJUThesis/assets/19789205/39bb676f-6329-43e1-b409-c86a3fbfe761)

### 最小工作示例

```TeX
原始版本，英文题目4行时问题挺大，第二导师也存在的话，直接变成两页了
```

### njuthesis 模板版本

V1.2.1

### 模板获取途径

通过 GitHub Releases 或镜像站下载

### 操作系统

Windows

### TeX 发行版

Tex Live2023

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
先在导言区加个补丁吧，之后我再找时间细调格式。

```tex
\EditInstance{nju}{cover-g-en}{format=\linespread{1.3}}
```

**Comment by atxy-blip** [comment]
修了。
