### ISSUE TITLE
[Bug]: 在论文摘要部分“仓”字会被编译成“仑”字

### ISSUE THREAD

**Issue by TianqiCai** [nju-lug/NJUThesis#220]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

应当将仓字编译成仓

### 发生了什么

![MBO{@}`68U`KFXW5Z04VJ0L](https://github.com/nju-lug/NJUThesis/assets/128724981/5db93a14-537b-477a-910a-ef27ed7d5a9c)

### 最小工作示例

```TeX
\begin{abstract}
  本文研究智能仓储中货物移位规划及对应的AGV(Automated Guided Vehicle)路径规划问题，又可被称为SRAP(Storage Relocation Assignment Problem)问题。当仓库内物品的需求或是价值发生较大改变时，对仓内物品进行移位操作可以增加物品的总价值。学者主要对物品是否进行移位操作及其目的地的选择，以及在已知移位目的地的基础上进行路径规划两方面进行了研究，但目前仍缺乏将二者同时进行考虑的研究。本文结合了这两方面的问题，同时考虑当下智能仓储的标准化存储的背景，设计AGV可同时搭载多个物品进行移动。以最大化移位后物品总价值，最小化AGV的移动路径以及最小化总移位次数作为优化目标，满足AGV最大装载物品数量要求和存储位置容量限制等约束，计算物品是否需要移位操作，移位目的地及AGV的移动路径。本文首先给出了该问题的整数规划模型，通过分析该模型可以得知直接求解模型的计算量过大，因此本文还提出了一种简化的二阶段整数规划模型。针对这两个阶段的子问题，本文分别提出了自适应性的大邻域搜索算法和禁忌算法以进行求解。最后，本文随机生成仓库数据与物品信息的数据集，并利用该方法对本文提出的整数模型和启发式算法进行数值实验。通过实验确定了模型中参数的最优取值，并通过比较启发式算法求得解与整数模型取得精确解，证明了启发式算法对该问题的有效性和算法效率的优越性。
  
\end{abstract}
```

### njuthesis 模板版本

v1.1.2

### 模板获取途径

<https://tex.nju.edu.cn>

### 操作系统

Windows

### 编译程序

XeLaTeX

**Comment by TianqiCai** [comment]
我在全新的模板中又试了一次，同样会发生该问题
![8HV})}`ATOFCWY4J)S6NQYX](https://github.com/nju-lug/NJUThesis/assets/128724981/27a89131-65e6-4878-b015-cc5cf41104b4)

**Comment by atxy-blip** [comment]
“最小工作示例”的介绍上说明了要完整包含 `\documentclass` 到 `\end{document}`，而不是随意的代码片段。

但显然这个问题是 Fandol 字体固有的，调成真正的 Windows 设置就可以了。

```
\documentclass[latin-font = win, cjk-font = win]{njuthesis}
\begin{document}
\begin{abstract}
仓仓仓仓仓仓仓仓
\end{abstract}
\end{document}
```
