### ISSUE TITLE
[Bug]: 专业学位的论文出版授权书“论文级别”选框未被勾选

### ISSUE THREAD

**Issue by snewpeap** [nju-lug/NJUThesis#223]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

专业硕士/博士学位的论文出版授权书中，“论文级别”一栏应勾选上“专业学位硕士/博士”选框

### 发生了什么

设置为专业学位（degree=professional）时，论文出版授权书的“论文级别”相应选框未被勾选
![QQ截图20230601195034](https://github.com/nju-lug/NJUThesis/assets/37863784/a5d4035d-d1eb-481b-aba6-efb4b221970f)

### 最小工作示例

```TeX
\documentclass[type=master,degree=professional,decl-page]{njuthesis}
\begin{document}
%...
\end{document}
```

### njuthesis 模板版本

v1.3.0

### 模板获取途径

<https://tex.nju.edu.cn>

### 操作系统

None

### 编译程序

XeLaTeX

### 额外信息

疑似问题代码，未覆盖opt_academic_bool==false && <span>#</span>1==false的case

https://github.com/nju-lug/NJUThesis/blob/b3d4c24bf5927b038bef5d4066aece96c629744f/source/njuthesis.dtx#L7040

**Comment by atxy-blip** [comment]
修好了。
