### ISSUE TITLE
[Bug]: 换了新的摘要页模板后，英文标题手动换行会出错

### ISSUE THREAD

**Issue by elem-azar-unis** [nju-lug/NJUThesis#227]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

英文摘要页的论文标题不要出问题

### 发生了什么

下面是英文标题的设置：
![image](https://github.com/nju-lug/NJUThesis/assets/11629021/319dcba4-ce10-49f6-8ea2-8fb1efd57ddc)

下面是摘要页的英文标题：
![image](https://github.com/nju-lug/NJUThesis/assets/11629021/30755a0d-1158-44c6-b1b2-58df7bd2d3de)

### 最小工作示例

```TeX
见**发生了什么**
```

### njuthesis 模板版本

v1.3.0

### 模板获取途径

通过 GitHub Releases 或镜像站下载

### 操作系统

Windows

### 编译程序

XeLaTeX

**Comment by elem-azar-unis** [comment]
> 修了。

准备发release吗，还是最近不会发了我直接clone好了

**Comment by atxy-blip** [comment]
现在可以从 <https://github.com/nju-lug/NJUThesis/actions/runs/5924875459> 的 Artifacts 板块下载每次 commit 生成的模板格式文件。
