### ISSUE TITLE
[Bug]: 副导师报错

### ISSUE THREAD

**Issue by JackokieZhao** [nju-lug/NJUThesis#230]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

之前副导师没有问题，新版本出错了

### 发生了什么

之前副导师没有问题，新版本出错了

### 最小工作示例

```TeX
supervisor-ii = {第二导师姓名,副教授},
   supervisor-ii* = {Associate professor My Second Supervisor},
```

### njuthesis 模板版本

v1.3.1

### 模板获取途径

从 Git 仓库下载

### 操作系统

Windows

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
<https://github.com/nju-lug/NJUThesis/commit/956dd17174d2f2b669ce7314a128e962af64c8b0> 迁移版本的时候改漏了。在 `njuthesis.cls` 第 49 行后面补一行命令吧，大概像下面这样：
```
\@ifpackagelater { expl3 } { 2023/10/10 } { }
  {
    \cs_generate_variant:Nn \tl_set:Nn        { Ne }
    \cs_generate_variant:Nn \tl_const:Nn      { Ne }
    \cs_generate_variant:Nn \tl_gput_right:Nn { Ne } % NEW
  }
```

**Comment by JackokieZhao** [comment]
还有一个问题：参考文献无法在正文中引用

**Comment by atxy-blip** [comment]
与本 issue 标题不相关的问题请单独开贴提问。参考问题建议先看手册，尤其是 3.6 节的参考文献部分：

> 本模板默认载入 biblatex 宏包，使用 biber 作为后端，通过 biblatex-gb7714-2015[15] 实
现 GB/T 7714–2015 [10] 规定的参考文献著录规则国家标准。需要使用 biber 命令编译才会显
示正确的条目序号，详情请参照第 2.3.3 节。本节提供的所有选项均基于此方案。
> 出于简化命令的考虑，本模板并不计划支持 BibTeX，但您可以通过第 3.2.4 节提供的选项
禁用默认的参考文献工具，自行利用 gbt7714 等宏包完成参考文献样式的配置。
