### ISSUE TITLE
[Feature]: 专业学位封面及摘要优化

### ISSUE THREAD

**Issue by liudongmiao** [nju-lug/NJUThesis#232]
### 先决条件

- [X] 我已尝试更新模板版本

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

在 https://github.com/nju-lug/NJUThesis/issues/208 中，为了解决专业学位封面的“专业学位类别(领域)”与摘要页面的“专业”不同问题，直接硬编码了专业学位中不写全称的情况下为“工程硕士”。

文档中指出：研究生的专业型学位封面上，“专业学位类别 (领域)”一栏默认会补全为“专业硕/博士（⟨专业⟩）”。如果希望覆盖模板的自动处理，可以填写 info/major 第二种写法的“专业全称”字段。

但是，有以下不妥之处：
1. 对于专业学位，虽然专业学位封面的“专业学位类别(领域)”与摘要页面的“专业”不同，实际上对于专业学位也可能一样；
2. 对于专业学位，如果一样，那么输入将变成 `major={XX专业，XX专业}`，两个一样，使用不优雅

此外，现在实现情况，等于为：
`专业硕士学位`如果为`major={XX专业}`的情况下，封面为`工程硕士(XX专业)`，硬编码了`工程`二字，而对于一样的情况，则需要使用`major={XX专业,XX专业}`来解决，两个一样，使用不优雅。

### 提出可能的解决方案

对于专业学位的 major 字段，采取以下方式，并在文档中给出：

`major={封面专业[,摘要专业]}`，`摘要专业`为可选，当不填时，封面与摘要专业一样；如果出现不一样，则使用不同值。（当然，也可以继续使用现在的 `major={摘要专业[,封面专业]}` 方案，只是当`封面专业`没有指定的情况下，不要硬编码为 `工程硕士(摘要专业)`。

此外，文档的 updated 日期是 `2023/05/11`，实际上此功能引入的版本号为 `1.3.0`，发布日期为 `2023/06/11`。

### 额外信息

此外，国家2018年起，工程硕士全面改革，分为不同的几个招生门类。
http://www.moe.gov.cn/srcsite/A22/yjss_xwgl/moe_818/201803/t20180326_331244.html

南大也于 2020 年停止招生工程硕士： https://grawww.nju.edu.cn/55652/list.htm

也就是说，对于南大工程硕士而言，最后毕业基于应当是 2019 + 5，也就是 2024 年，此后应当是不存在 工程硕士 了（延毕应该没有学位了吧....）。

**Comment by atxy-blip** [comment]
改了。

> 此外，文档的 updated 日期是 `2023/05/11`，实际上此功能引入的版本号为 `1.3.0`，发布日期为 `2023/06/11`。

这里是按 commit 时间填写的。
