### ISSUE TITLE
[Bug]: 定理环境共享计数器时，cref出错

### ISSUE THREAD

**Issue by tsdjh** [nju-lug/NJUThesis#234]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

添加了
\njusetup[theorem]{
share-counter = true,
define
}
并且使用了lemma环境之后，用\cref{}命令，期望生成：引理1.1

### 发生了什么

添加了
\njusetup[theorem]{
share-counter = true,
define
}
并且使用了lemma环境之后，用\cref{}命令，实际生成：公理1.1
似乎是因为初始定义的7个定理环境之中，axiom 公理 排第一个

### 最小工作示例

```TeX
\documentclass{njuthesis}
\input{njuthesis-setup.def}
\njusetup[theorem]{
share-counter = true,
define
}
\begin{document}
\mainmatter
\begin{lemma}\label{lem:1}
\end{lemma}
\cref{lem:1}
\end{document}
%似乎需要运行两遍XelateX，否则出现??
```

### njuthesis 模板版本

v1.3.2

### 模板获取途径

<https://tex.nju.edu.cn>

### 操作系统

Windows

### TeX 发行版

MiKTeX 23.1

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
拿下面的例子测了一下，发现可能是 `cleveref` 载入过程出了点问题。之后慢慢排查吧。

```tex
% \documentclass{njuthesis}
\documentclass[cleveref=false]{njuthesis}
\usepackage{cleveref}
\newtheorem{axiom}{公理}
\newtheorem{lemma}[axiom]{引理}
\crefname{axiom}{ax}{ax}
\crefname{lemma}{lm}{lm}
\begin{document}
\mainmatter
\begin{lemma}\label{lem:1}
\end{lemma}
\cref{lem:1}
\begin{axiom}\label{ax:1}
\end{axiom}
\cref{ax:1}
\end{document}
```

> 似乎需要运行两遍XelateX，否则出现??

第一遍写入 `.aux` 文件的交叉引用信息，在第二次编译才能生成到文档中。

**Comment by atxy-blip** [comment]
修了但最近 ssh 裸连 GitHub 不通了，得再想办法才能 push 上去。

实际上只要把 `ntheorem` 放到 `hyperref` 和 `cleveref` 前面就可以。

https://github.com/nju-lug/NJUThesis/blob/6ced18aff3a1e64d7cb143b25d1715a578c2e04b/source/njuthesis.dtx#L4300-L4316

**Comment by tsdjh** [comment]
非常感谢！请问我具体需要怎么做才能用上修改后的版本呢？

**Comment by atxy-blip** [comment]
下载 GitHub Actions 生成的 Artifacts (<https://github.com/nju-lug/NJUThesis/actions/runs/7559649885>) 或者克隆仓库后运行 install 脚本。

**Comment by tsdjh** [comment]
好了，非常感谢您的帮助！
