### ISSUE TITLE
模板的建议

### ISSUE THREAD

**Issue by Vodkazy** [nju-lug/NJUThesis#24]
感谢各位contirbutors的工作！有个小建议，github上其实有一些祖传的完整度比较高的NJU Latex模板，例如：https://github.com/njuHan/njuthesis-nju-thesis-template（基于https://github.com/Haixing-Hu/nju-thesis） ，是不是可以考虑集成到NJUThesis里来 :)

**Comment by atxy-blip** [comment]
其实现在这个模板原本就是衍生自胡海星前辈的项目哦。

在去年，@FengChendian对胡学长的模板进行了修改，得到了符合当时标准的[NJU Thesis 2021](https://github.com/FengChendian/NJUThesis2021)。显然修改过程不太顺利，出现了一些比较恼人的问题：

- 缺少注释和说明文档以及空格分隔
- 结构臃肿，频繁定义新的宏
- latex2e语法日渐过时

Feng也因此发起了目前的重构计划，而且最初的代码是从前述的模板删节分块得到的，随后才使用latex3语法进行了大幅度的改编。现在也有一些痕迹能指向胡学长的工作，最明显的莫过于国家图书馆封面的绘制命令。

**Comment by atxy-blip** [comment]
问题已经解答，此issue将关闭。
