### ISSUE TITLE
本科论文模板四级标题添加编号

### ISSUE THREAD

**Issue by Cabdog** [nju-lug/NJUThesis#255]
### 先决条件

- [X] 我已尝试更新模板版本
- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)
- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)
- [X] 我已确认这个请求没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。

### 现有模板的不便之处

使用\subsubsection{}作为四级标题时不生成如1.1.1.1的编号

### 提出可能的解决方案

希望\subsubsection{}能作为四级标题时生成如1.1.1.1的编号

**Comment by AvoidAcid** [comment]
试试
```
\setcounter{secnumdepth}{3}
```

**Comment by atxy-blip** [comment]
这是 `ctex` 提供的设置，见 [`ctex` 宏集手册](http://mirrors.ctan.org/language/chinese/ctex/ctex.pdf) 16 页，在导言区加 `\ctexset{secnumdepth=3}`，和 @AvoidAcid 提供的设置等价。相应的目录层级设置是 `tocdepth`。

<img width="656" alt="image" src="https://github.com/nju-lug/NJUThesis/assets/63113546/bc732186-dc65-4950-94d6-a0af382693ad">

**Comment by Cabdog** [comment]
已解决，感谢！
