### ISSUE TITLE
[Bug]: 表格编译错误，或者单元格内容无法垂直居中

### ISSUE THREAD

**Issue by qleenju** [nju-lug/NJUThesis#264]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)
- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)
- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)
- [X] 我已确认这个问题没有在[其他 issues](https://github.com/nju-lug/NJUThesis/issues) 中提出过。

### 期望的现象

在nju tex网站上使用模板，期望生成一个可以正确编译，且单元格内容垂直居中的表格，但一直出现问题，在使用\begin{tabular}环境时出现编译报错；在使用\begin{tblr}环境时出现单元格内容无法垂直居中显示。

### 发生了什么

如下表格，在南大模板中编译报错，实在找不到问题：
````
\begin{table}
\centering
\begin{tabular}{|c|l|} 
\hline
es & \multicolumn{1}{c|}{Meaning} \\ 
\hline
000-001 & Input es values \\ 
\hline
100-110 & Invalid, Reserved for future use \\ 
\hline
111 & \begin{tabular}[c]{@{}l@{}}In instruction's es field, select dynamic es values in pcsr;\\In pcsr register, Invalid.\end{tabular}  \\
\hline
\end{tabular}
\end{table}
````
最终编译生成的表格如下所示：
![image](https://github.com/user-attachments/assets/c41847fb-60cc-47ca-972a-d7a31ad0709f)
报错信息如下所示（实在没搞懂该报错到底是什么意思）：
![image](https://github.com/user-attachments/assets/cb8b81ba-da53-4914-90bb-03a1f292f460)

于是我换了一种表格生成方法，代码如下：
```
\begin{table}
\centering
\begin{tblr}{
  row{1} = {c},
  cell{2}{1} = {c},
  cell{3}{1} = {c},
  cell{4}{1} = {c},
  hlines,
  vlines,
}
es & Meaning \\
000-001 & Input es values \\
100-110 & Invalid, Reserved for future use \\
111     & {In instruction's es field, select dynamic es values in pcsr;
\\In pcsr register, Invalid.} 
\end{tblr}
\end{table}
```
此时可以编译正确，但是单元格第四行第一列的内容始终无法做到垂直居中，即使我照着网上给出的方法，比如设置`cell{4}{1} = {c, m}`，或者第四行111的内容单独加上如下语句`\SetCell{valign = m}111`，但都均无果：
![image](https://github.com/user-attachments/assets/d4e3b7de-7763-4a81-9b9b-3d57ed56351d)

### 最小工作示例

```TeX
\
```

### njuthesis 模板版本

v1.4.1

### 模板获取途径

<https://tex.nju.edu.cn>

### 操作系统

Windows

### 编译程序

XeLaTeX

**Comment by atxy-blip** [comment]
事实上这不是一个 bug……

首先，`tabular` 环境不推荐嵌套使用，也就是你不能在一个 `tabular` 里面放另一个 `tabular`。如果你感兴趣的话可以研究一下 `multicolumn` 包的用法，在这里就不展开了。

然后是 `tabularray` 的用法问题，只是你参数没给对。如果你指定 111 所在的单元格使用 `m` 的垂直对齐，那后面一长串字符仍然以 111 所在的基线进行顶部对齐，结果就是 111 被挤到了上面。所以你需要给整行加上 `m` 的垂直对齐，详见下面例子：

```tex
\documentclass[draft]{njuthesis}
\usepackage{tabularray}

\begin{document}
\begin{table}
\centering
\begin{tblr}{
  hlines,
  vlines,
  colspec = {cl},
  cell{1}{2} = {c},
  row{4} = {m}
}
es & Meaning \\
000-001 & Input es values \\
100-110 & Invalid, Reserved for future use \\
 111 & 
 {In instruction's es field, select dynamic es values in pcsr;
\\In pcsr register, Invalid.}      
\end{tblr}
\end{table}

\end{document}
```

![image](https://github.com/user-attachments/assets/3e69d9e0-574b-445a-8fab-2114d4369e04)

**Comment by qleenju** [comment]
好嘞，已解决。

**Comment by qleenju** [comment]
感谢感谢！
