### ISSUE TITLE
documentclass degree 适配问题

### ISSUE THREAD

**Issue by FeynmanCheng** [nju-lug/NJUThesis#27]
修改 `\documentclass` degree 为 mf, ug, mg 均会出现下图所示类似情况， 150pt , 14em 之类

我在南大 overleaf 编译的

![image](https://user-images.githubusercontent.com/48194659/133284831-acf942b0-079d-4533-8088-b6ac28e38060.png)

**Comment by atxy-blip** [comment]
之前由于`\str_case_e:nn`可能比较慢就换成了`\str_case:Nn`，然而后者是非法的。不久前在改本科版本的样式所以没在意，属于百密一疏了。

更改已提交，请在稍后查看Releases区的新版本。种种不便，敬请谅解。

问题已解决，本issue将关闭。
