### ISSUE TITLE
引用编译错误 + 研究生英文封面

### ISSUE THREAD

**Issue by lina-luck** [nju-lug/NJUThesis#28]
感谢分享！

1. 是否支持多个bib文件

2. 研究生毕业论文包含英文封面，该版本似乎没有。

谢谢。

**Comment by atxy-blip** [comment]
> 是否支持多个bib文件

请参考[这个链接](https://tex.stackexchange.com/questions/21439/is-there-any-advantage-to-using-addbibresource-over-bibliography)。额外的bib文件多调用一次命令即可，注意不要漏掉扩展名。
```
\addbibresource{file1.bib}
\addbibresource{file2.bib}
```

> 研究生毕业论文包含英文封面，该版本似乎没有。

比较抱歉的是这个模板更新得比较勤快，其实前天的0.9.2版已经加上了这个功能，刚刚有更新0.9.3修复了目录问题并丰富了文档orz 请注意参考新版`njuthesis-sample.tex`，英文封面额外带来了一两个需要填写的信息项。

**Comment by lina-luck** [comment]
了解了，万分感谢！

**Comment by atxy-blip** [comment]
嗯嗯，感谢支持！

俺觉着这个问题已经解决了，此贴关闭。
