### ISSUE TITLE
最新版本引用出错

### ISSUE THREAD

**Issue by lina-luck** [nju-lug/NJUThesis#30]
添加自己的引用之后报错，请问该如何处理？

另外，添加\usepackage{subfigure} 也报错

**Comment by atxy-blip** [comment]
不知为何这个issue被你关了，导致一直没看到…

> 添加\usepackage{subfigure} 也报错

`subfigure` 包和用来修改目录格式的 `tocloft` 包存在一定冲突，虽然说后者提供了一个兼容选项。我在这里更推荐使用更新、语法更简洁的`subcaption`包，相关的支持和使用例已经提交到主仓库，有空的话可以看一看。
