### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by lina-luck** [nju-lug/NJUThesis#39]
抱歉又是我，发现几个小问题

1. 英文封面不能添加第二导师
2. 没有成果列表页面
3. 默认的数学花体字母不是标准显示的花体，参见https://www.caam.rice.edu/~heinken/latex/symbols.pdf  中的11节

**Comment by atxy-blip** [comment]
> 英文封面不能添加第二导师

这个确实是疏忽，已在[https://github.com/nju-lug/NJUThesis/commit/ec3b69b4ae46380f55f007f5f69e9131986f2958](最新提交)解决。

> 没有成果列表页面

由于手边并没有相关的参照文件，请问可否提供一份范本来指导这个成果列表的格式？

**Comment by lina-luck** [comment]
请问需要什么样的范本？pdf还是latex？

**Comment by atxy-blip** [comment]
> 请问需要什么样的范本？pdf还是latex？

需要已经排版好的PDF格式文档，方便照葫芦画瓢。另一方面，如果有供测试用的TeX格式的成果条目更好。

**Comment by lina-luck** [comment]
怎么提供呢？ 可以私信吗？

**Comment by atxy-blip** [comment]
> 默认的数学花体字母不是标准显示的花体

已通过添加 `amssymb` 包修复

> 怎么提供呢？ 可以私信吗？

网页版 Github issue 输入框下方可以拖拽添加附件。

**Comment by lina-luck** [comment]
[paperlist.pdf](https://github.com/nju-lug/NJUThesis/files/7244768/paperlist.pdf)
[test.txt](https://github.com/nju-lug/NJUThesis/files/7244771/test.txt)

tex 文件不支持，你将就着看看。还是感觉可以区分一下第一作者和合作发表的成果。感谢！

**Comment by glatavento** [comment]
你好，我对数学排版这一块的要求不太熟悉，所以请教两个问题
1. 是否对普通公式中使用的字体有要求？比如下面两张图就分别使用了不同的字体，这两种字体哪种更符合标准？
![computer modern](https://user-images.githubusercontent.com/76601050/135108353-869beedc-2d95-4a69-9fc1-cd66bd256ea2.png)
![times new roman](https://user-images.githubusercontent.com/76601050/135108491-27d04a75-8e43-4595-9648-e9e246552e62.png)

2. 是否需要添加数学字体选择功能？如果需要，是否需要添加细粒度的数学字体选择功能（为bb、cal等单独选择字体）

**Comment by lina-luck** [comment]
1. 两种都见到过，我发的那个latex数学公式标准使用的是第一个吧。
2. 不需要添加吧，个人感觉就用标准的就可以了。

感觉没必要太纠结，只要能理解就可以。只是原来那个花体实在是太“花”了，跟平常用的不太一样。
