### ISSUE TITLE
使用TexStudio编译报错package is too old

### ISSUE THREAD

**Issue by zsnjuts** [nju-lug/NJUThesis#48]
我用的是texlive2021最新版，编译报错如下
![image](https://user-images.githubusercontent.com/16850617/144576182-8c9531ed-0fbe-4419-97e2-5439ddd6005a.png)

**Comment by atxy-blip** [comment]
这是因为用了一些 LaTeX3 的新特性，所以内置了一个强行版本检查。解决办法是在终端运行
```
tlmgr update l3packages
```

不过感谢反馈，确实把版本设置太新是个问题。对于 TeX Live 2021 理应实现开箱即用，稍后会重新提交 0.12.2 版放宽这个检查。

**Comment by atxy-blip** [comment]
修复后的版本已发布，请前往 Releases 页面获取。

**Comment by zsnjuts** [comment]
可以用了，感谢！
