### ISSUE TITLE
算法伪代码环境异常

### ISSUE THREAD

**Issue by runninglsy** [nju-lug/NJUThesis#49]
您好，我在使用算法环境algorithm时出现异常，提示algorithm已被定义，在移除cls文件里面的algorithm定义后能正常编译，但是伪代码前后都有额外的空白，猜测是cls文件里某些设置影响到了algorithm包，自己尝试了一些方法都没解决，希望能在这里得到帮助，谢谢！

latex代码：
\begin{algorithm}[tbp]
    \caption{Temp} 
    \begin{algorithmic}[1]
    \STATE Temp
    \end{algorithmic}
\end{algorithm}

PDF：
![image](https://user-images.githubusercontent.com/24290613/144735477-ac6d7a4a-114b-48d1-9501-3b3dfc20e492.png)

**Comment by runninglsy** [comment]
定位到了是floatrow和algorithm里用到的float包冲突。现在临时的解决方法是删除掉cls文件里的\RequirePackage{floatrow}，以及floatsetup相关的代码，将captionsetup中的skip相关参数改为aboveskip=10pt, belowskip=0pt。

**Comment by atxy-blip** [comment]
怪我，那部分是从一个旧项目抄来的，一直没改orz

> 定位到了是floatrow和algorithm里用到的float包冲突。

感谢排查！

> 将captionsetup中的skip相关参数改为aboveskip=10pt, belowskip=0pt。

问题出在 `\captionsetup` 设定了一个全局的样式，覆盖了 `algorithm` 环境的定义。接下来会把特定设置限制在 `figure` `table` `lstlisting` 三个环境内。

**Comment by atxy-blip** [comment]
好蠢，GitHub Action 出问题导致搞出了这么多 commit…

问题已经得到了修复，可以使用仓库中的脚本释放文件使用。
