### ISSUE TITLE
[FEATURE] 增加选项以方便更改mathcal和mathbb字体为计算机论文中的常用样式

### ISSUE THREAD

**Issue by runninglsy** [nju-lug/NJUThesis#51]
**现有模板的不便之处**
现有模板基于Unicode-math引入的数学字体中，mathcal字体与常用的版本（也是latex默认的版本）不符，mathbb字体也与很多英文论文模板（如ICML，AAAI）里的字体不同。

**提出可能的解决方案**
增加选项重置mathcal字体为latex默认的版本，更改mathbb为New Computer Modern Math字体

**提出考虑过的方案**
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\setmathfont{NewCMMath-Regular.otf}[range={bb}]

**额外信息**
参见https://github.com/UCL/ucl-latex-thesis-templates/issues/19

**Comment by atxy-blip** [comment]
已在 https://github.com/nju-lug/NJUThesis/commit/ba3aee9daf57a5ba7c36952d3c09ae3d0d5b2b7a 中修复。
