### ISSUE TITLE
怎么样能够把标题中的英文和数字改成times new roman字体

### ISSUE THREAD

**Issue by fantasyEthan** [nju-lug/NJUThesis#56]
规范中确实规定标题为黑体，不过目录中的数字也采用了roman字体，一般数字和英文也都采用Roman字体；而且标题中的黑体英文确实不是很美观；希望能够有更改的方法（原来的黑体也可以继续使用

**Comment by atxy-blip** [comment]
使用 `\textrm` 命令定义为罗马字体族即可。MWE 如下所示：

```
\documentclass{njuthesis}
\begin{document}
\mainmatter
\chapter{生命 \textrm{the Universe} 以及一切}
\end{document}
```

此外，指定无衬线字体族（即 Arial 字体）可使用 `\textrsf` 命令。这个只能请你手动修改一下自己的标题，目前不打算在模板中进行样式修改。

**Comment by fantasyEthan** [comment]
> 使用 命令定义为罗马字体族即可。MWE 如下所示：`\textrm`
> 
> ```
> \documentclass{njuthesis}
> \begin{document}
> \mainmatter
> \chapter{生命 \textrm{the Universe} 以及一切}
> \end{document}
> ```
> 
> 此外，指定无衬线字体族（即 Arial 字体）可使用 命令。这个只能请你手动修改一下自己的标题，目前不打算在模板中进行样式修改。`\textsf`

好的，谢谢解答
