### ISSUE TITLE
Package array Error: Illegal pream-token (|): `c' used. ^^I^^I^^I\begin{tabular}{|c|c|c|c|c|c|c|}

### ISSUE THREAD

**Issue by Kylin0123** [nju-lug/NJUThesis#58]
**描述**
编译表格出错

**最小工作示例**
```
\begin{table}[htbp]
	\setlength{\belowcaptionskip}{7pt}
	\centering
	\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|}
		\hline
		&   & 国 & 内 & 企 & 业 & 包 & 括 & 许 & 多 \\
		\hline
		& 0 & 1  & 2  & 3  & 4  & 5  & 6  & 7  & 8  \\
		\hline
		国 & 1 & 0  & 1  & 2  & 3  & 4  & 5  & 6  & 7  \\
		\hline
		著 & 2 & 1  & 1  & 2  & 2  & 3  & 4  & 5  & 6  \\
		\hline
	\end{tabular}
	\vspace{0.2cm}
	\caption{编辑距离（乐文斯汀距离计算过程示例表格。字符串``国内企业包括许多''与``国著名括许多''乐文斯汀距离是3。}\label{table:ld}
\end{table}
```

**截图**
![image](https://user-images.githubusercontent.com/21048175/148953142-90491a25-5e47-406c-b228-af0da51c64c8.png)

**平台信息**
在发生编译问题时提供。
 - 操作系统：Windows 10
 - TeX 发行版：TeX Live 2021
 - 编译命令：xelatex

**Comment by atxy-blip** [comment]
啊……这个问题是因为上传 CTAN 的 v13.0 存在一些小问题，内置的 `listings` 默认将 | 作为抄录环境分隔符了。稍后的提交已经解决了这个问题。

您可以将新版本的 `.cls` 文件放在当前编译目录下来覆盖安装的版本，这个文件的获取途径有
- Releases 页面提供的压缩包
- 仓库中的 install 脚本

当然，`bib` 分支的 v0.14 已经基本做好了，还差一些与校内在线 TeX 编译网站的合作内容就可以上传 CTAN，争取过年前搞定。

**Comment by Kylin0123** [comment]
用bib分支中最新的dtx以后正常了，感谢感谢
