### ISSUE TITLE
[FEATURE] 合并导师姓名职称设置选项

### ISSUE THREAD

**Issue by atxy-blip** [nju-lug/NJUThesis#60]
目前模板的导师设置选项最开始是为构建本科封面编写的。本科生封面上将导师的姓名职称分开，很自然地产生了两个选项。然而，研究生需要英文封面，前面说的两个选项就变成了四个；再加上可能有的双导师配置，就变成了八个，显然太多了。另一方面，仅仅是本科生封面要求分开填写，其余所有的包括摘要、研究生封面都是将导师的姓名职称合并呈现的。

目前想法是采取 `!` 作为姓名职称的分隔符，在本科模板中使用正则表达式分割，在研究生模板中直接替换成空格。

-------------------------

顺手发现了一个 bug：目前本科生封面第二导师的职称内容会输出为第一导师的。

**Comment by zepinglee** [comment]
可以用逗号作为分隔符：`supervisor = {name, title}`，这样可以直接用 clist 处理。

**Comment by atxy-blip** [comment]
> 可以用逗号作为分隔符

感谢点拨！直接写好提交了。
