### ISSUE TITLE
[FEATURE] 术语表页&表格的格式问题

### ISSUE THREAD

**Issue by FeynmanCheng** [nju-lug/NJUThesis#61]
**现有模板的不便之处**

希望能在正文前添加一页术语表，形式如同前言页。且该页中的表格不被表目录页统计，也不需要给这个表编号

表格好像不会自动换行，若一行内容过多会超出右页边距。

**Comment by atxy-blip** [comment]
此易耳，隔壁 `fduthesis` 有术语表功能，这两天就去借鉴一下。

**Comment by atxy-blip** [comment]
> 表格好像不会自动换行，若一行内容过多会超出右页边距。

不同的内容请另开新的 issue 讨论。

表格中确实不便于换行，如果内容过长可以试试用 `rotating` 宏包提供的旋转表格功能。

**Comment by atxy-blip** [comment]
新功能已提交。

关于”术语表“还是”符号表“这个标题问题，之后会将文本常量定义分离成单独的 `.def` 文件以便自定义。
