### ISSUE TITLE
博士论文模板开启国家图书馆封面后，原先的封面页（带校名和校徽）不显示

### ISSUE THREAD

**Issue by yanzhibo-nju** [nju-lug/NJUThesis#62]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues) 中提出过。

### 期望的现象

开启国家图书馆封面后，国家图书馆封面和原先的封面页都显示

### 发生了什么

博士论文模板开启国家图书馆封面后，原先的封面页（带校名和校徽）不显示

### 最小工作示例

```TeX
degree = phd,
nlcover = true,
```

### njuthesis 模板版本

0.14.0

**Comment by atxy-blip** [comment]
这个是 feature 而不是 bug。

事实上，手册里关于 `nlcover` 选项的介绍是这样写的：

> 通过此项可用国家图书馆封面*替换*普通封面。

我找隔壁桌刚拿到博士学位的师姐借了她的论文，国家图书馆封面和南京大学封面是分开的两本，分别有不同的用途。如果希望同时生成两种封面，模仿下面例子在 `\makecover` 前面打个补丁吧：

```TeX
\documentclass[degree=phd]{njuthesis}
\begin{document}
\ExplSyntaxOn
\pagestyle{empty}
\__nju_make_cover_nl:
\cleardoublepage
\ExplSyntaxOff
\maketitle
\end{document}
```
 > MWE 本意如此，一个 minimal 的文档。刚刚发现研究生封面有一个在不填个人信息时会多余的换行符，以上在编译时需要手动忽略 error。
