### ISSUE TITLE
博士论文模板，页眉内容完善

### ISSUE THREAD

**Issue by yanzhibo-nju** [nju-lug/NJUThesis#63]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues) 中提出过。

### 期望的现象

查阅了多篇博士毕业论文，大多数页眉
左侧：“南京大学博士毕业论文”
右侧：章节内容如“第一章 绪论”

且不分奇偶页，与项目文档修订记录中描述的研究生模板页眉样式不同

### 发生了什么

当前页眉显示在中间

### 最小工作示例

```TeX
degree = phd,
```

### njuthesis 模板版本

0.14.0

**Comment by yanzhibo-nju** [comment]
博士论文的页眉 好多都不同

**Comment by atxy-blip** [comment]
稍微提醒一下，该 issue 中标记的是 v0.14.0，而修订记录中关于页眉的记录在 *[未发布]* 中。

研究生院对这个本来也没有统一的规定。希望自行修改的话，手册后半部分可以找到使用 `fancyhdr` 宏包定制页眉格式的代码，在正文中覆盖这个设置就行。
