### ISSUE TITLE
[Bug]: v0.14.0版本取消第二导师的注释之后没有显示

### ISSUE THREAD

**Issue by wang12d** [nju-lug/NJUThesis#64]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues) 中提出过。

### 期望的现象

学硕毕业论文模板`degree=mg`，使用是nju tex，编译器版本选择的是`texlive-full:2020.1`，编译选项尝试过`XeLaTex`和`LuaLaTex`. 但是在生成的pdf文件中都没有出现第二导师的信息.

### 发生了什么

![image](https://user-images.githubusercontent.com/23007430/150643548-48a87e22-8db8-4b1b-b7f9-b0ad97d00ce2.png)
![image](https://user-images.githubusercontent.com/23007430/150643517-ee096ad6-f2d8-4d6e-81d7-826e06370403.png)
![image](https://user-images.githubusercontent.com/23007430/150643530-81afb8ad-8389-4d60-9d9d-0a7d408c62bd.png)
![image](https://user-images.githubusercontent.com/23007430/150643774-bcfe3319-6802-40b1-915c-b9c245d26258.png)

### 最小工作示例

```TeX
\documentclass[degree=mg]{njuthesis}

\njusetup {
    info = {
        title = {第一行标题\\第二行标题\\第三行标题},
        title* = {My Title in English},
        author = {姓名},
        author* = {Ming Xing},
        keywords = {我,就是,充数的,关键词},
        keywords* = {Dummy,Keywords,Here,{It Is}},
        grade = {2017},
        student-id = {123456},
        department = {计算机科学与技术},
        department* = {Department of Computer Science},
        major = {计算机科学},
        major* = {Computer Science},
        supervisor = {第一导师,教授},
        supervisor*= {Professor Supervisor},
        supervisor-ii = {第二导师,副教授},
        supervisor-ii* = {Associate professor Second Supervisor},
        submit-date = {2021-08-10},
        field = {物理化学},
        field* = {Physical Chemistry},
        defend-date = {2021-09-19},
        chairman = {某某某~教授},
        reviewer = {
            某某某~教授,
            某某某~教授
        },
        clc = {0175.2},
        secret-level = {限制},
        udc = {004.72},
        supervisor-contact = {
            南京大学~
            江苏省南京市栖霞区仙林大道163号
        }
        % 导师联系方式
    },
    bib = {
        resource = {njuthesis-sample.bib}
    },
    style = {
        emblem-img = {nju-emblem},
        name-img = {nju-name}
    }
}

\begin{document}


\maketitle

\begin{abstract}
    中文摘要
\end{abstract}

\begin{abstract*}
    English abstract
\end{abstract*}

\tableofcontents
\listoffigures
\listoftables
\mainmatter


\chapter{引言}

\section{tDMRG}

矩阵乘积态也被用于含时薛定谔方程的求解，形成了含时密度矩阵重整化群方法\cite{schollwock2011}。

\printbibliography

\begin{acknowledgement}
    感谢 \href{https://git.nju.edu.cn/nju-lug/lug-introduction}{LUG@NJU}。
\end{acknowledgement}
\appendix

\end{document}
```

### 操作系统

Windows

### 编译引擎

XeLaTeX

### njuthesis 模板版本

0.14.0

### 模板获取途径

使用包管理器从 CTAN 安装

**Comment by atxy-blip** [comment]
我爬。

下午 QQ 群有人反馈了。其实现在已经改得差不多了，明早就提交。

**Comment by atxy-blip** [comment]
已修复。在线 LaTeX 网站的模板不便于更新，如果急需的话可以使用开发版本。
