### ISSUE TITLE
目录定制

### ISSUE THREAD

**Issue by Otogra** [nju-lug/NJUThesis#66]
使用仓库里的 sample，目录如下图：
<img width="747" alt="image" src="https://user-images.githubusercontent.com/42164573/152473995-92d8f9cb-5d17-4d21-a3b5-56e3c97bb1fa.png">

请问怎么定制下面的样式：
1. 去掉目录中的中英文摘要
2. 目录中的 chapter 和页码之间有点号

**Comment by atxy-blip** [comment]
> 去掉目录中的中英文摘要

稍后会添加一个选项。

> 目录中的 chapter 和页码之间有点号

标准文档类 `book` 中没有对 chapter 绘制引导线。可以引入目录相关的宏包进行修改。下面是一个例子：

```
\usepackage{titletoc}
\titlecontents{chapter}[0pt]{\heiti\zihao{4}\vspace*{10pt}}{\thecontentslabel\hspace*{1em}}{}{~\titlerule*[0.8pc]{$.$}~\contentspage}
\titlecontents{section}[3em]{\vspace*{-5pt}}{\thecontentslabel\hspace*{1em}}{}{~\titlerule*[0.8pc]{$.$}~\contentspage}
\titlecontents{subsection}[5em]{\vspace*{-5pt}}{\thecontentslabel\hspace*{1em}}{}{~\titlerule*[0.8pc]{$.$}~\contentspage}
```

 (显然额外配置要麻烦一点)

另：不知为何要提交两条同样的 issue？

**Comment by Otogra** [comment]
@atxy-blip 谢谢回复

（第一个issue提成bug了，就close掉了

**Comment by atxy-blip** [comment]
添加了 `style/abstract-in-toc` 选项。

**Comment by lllwwwbbb** [comment]
对于目录中的”ABSTRACT“，我想替换成”英文摘要“这四个字，是否有选项可以设置？

**Comment by atxy-blip** [comment]
> 对于目录中的”ABSTRACT“，我想替换成”英文摘要“这四个字，是否有选项可以设置？

请不要在已经关闭的 issue 下提问。新的讨论内容请开新帖。
