### ISSUE TITLE
在每章后附上参考文献表

### ISSUE THREAD

**Issue by atxy-blip** [nju-lug/NJUThesis#79]
### Discussed in https://github.com/nju-lug/NJUThesis/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **zhoujian9410** February 13, 2022</sup>
参考文献较多，因此想分章节进行参考文献引用，想请教一下现在的模板能否实现这个目标呢？能的话应该如何设置？多谢各位大佬</div>

现有的模板可以实现，但是要在每章套上一个 `refsection` 环境，显然不够简洁，需要纵深满足用户需求，开创新打法，扩展产品路线。

第一想法当然是包装一下 `input`，很简单就能实现：

```TeX
\NewDocumentCommand \inputchapwithbib { s m }
  {
    \begin{refsection}
      \input {#2}
      \bool_if:nTF {#1}
        {
          \printbibliography
            [ title = \bibname, heading = subbibliography ]
        }
        {
          \printbibliography
            [ title = \bibname, heading = subbibintoc     ]
        }
    \end{refsection}
  }
```

如果再想想的话，参考文献表在哪里其实是一个全局的设置，加个 `style/bibafterchapter` 这样的开关也许就好？具体实现方面大概是在 chapter 开始和结束的钩子上挂载第一想法的代码就好。这个的困难在于本人还没搞清楚 LaTeX 的钩子机制 Orz

**Comment by hushidong** [comment]
可以在biblatex中使用refsection=chapter选项，但不知道会不会影响模板对chapter的重定义。可以尝试一下？
如果没有影响的话，那么就使用该选项，然后再章节末尾printbibliography就可以了。

**Comment by atxy-blip** [comment]
> 不知道会不会影响模板对chapter的重定义

模板未曾对带编号的章节加以改动，所以这个选项的作用效果是没问题的，

还有个小小的遗留问题。使用了这个设置后要使用这样的参数
