### ISSUE TITLE
[Bug]: 表格中单元格底色着色 xcolor 包引入错误

### ISSUE THREAD

**Issue by cvpr-submission** [nju-lug/NJUThesis#83]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues) 中提出过。

### 期望的现象

\usepackage[table,xcdraw]{xcolor}后
在正文中添加表格中使用\cellcolor[HTML]{ECF4FF}3
应当正确为单元格着色
(在小论文中是能正常使用的)

### 发生了什么

无法识别，并且报错
Latex Error：Option clash for package xcolor

### 最小工作示例

```TeX
\documentclass[]{njuthesis}
\usepackage[table,xcdraw]{xcolor}
\begin{document}

\begin{table}[]
\begin{tabular}{lll}
1 & 2 & 3 \\
1 & \cellcolor[HTML]{FE0000}3 & 5 \\
1 & 4 & 7
\end{tabular}
\end{table}

\end{document}
```

### TeX 发行版

TeX Live 2021

### 编译引擎

XeLaTeX

### njuthesis 模板版本

快更新吧

### 模板获取途径

通过 GitHub Releases 或镜像站下载

### 额外信息

overleaf编译 v0.15.0

**Comment by atxy-blip** [comment]
对于目前已有的 v0.15.0 版，把这两个选项放在全局的模板选项中就可以，形如

```TeX
\documentclass[table,xcdraw]{njuthesis}
\begin{document}
\begin{table}[htbp]
\begin{tabular}{lll}
1 & 2 & 3 \\
1 & \cellcolor[HTML]{FE0000}3 & 5 \\
1 & 4 & 7
\end{tabular}
\end{table}
\end{document}
```

事实上，报错信息说得很明白，只不过你没摘录全：

```
The package xcolor has already been loaded with options:
  []
There has now been an attempt to load it with options
  [table,xcdraw]
Adding the global options:
  ,table,xcdraw
to your \documentclass declaration may fix this.
```

-----

报错是因为，为了在任何情况下均能绘制校名校徽，模板默认载入了 `njuvisual` 包，而 `njuvisual` 包依赖 `tikz`，后者已经载入了 `xcolor`。为了使两个选项顺利传入 `xcolor`，理应使其在 `tikz` 前载入。然而，`njuvisual` 在导言区之前就已经载入，这就引发了顺序问题。

惊喜的是问题已经被我意外解决了。最近的几次提交中解除了对 `njuvisual` 的强制依赖。本意是简化安装脚本，但由于将其修改为在导言区末尾载入，因此不会出现顺序问题。根据我刚刚进行的测试，仓库中的版本是可以直接运行上述代码的。
