### ISSUE TITLE
[Bug]: 部分汉字无法显示出来

### ISSUE THREAD

**Issue by ClaraLiu410** [nju-lug/NJUThesis#93]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues) 中提出过。

### 期望的现象

能显示 珺 这个字

### 发生了什么

我的名字中含有 珺 这个字，但是在编译后无法显示出来，将编译后的PDF下载下来，珺字的位置显示为F。
使用的是南大在线编译网站，两种编译器都试过了，但都不行。

### 最小工作示例

```TeX
author = {xx珺}
```

### njuthesis 模板版本

0.15.0

### 模板获取途径

<https://tex.nju.edu.cn>

### 操作系统

macOS

### TeX 发行版

TeX Live 2021

### 编译引擎

XeLaTeX

**Comment by atxy-blip** [comment]
这是因为在线编译运行在 Ubuntu 系统下，默认调用 Fandol 中文字体，可能有缺字现象。我在测试时用的繁体例子缺了不少字。

```TeX
\documentclass[latin-font = win, cjk-font = win]{njuthesis}
```

载入 Windows 字体选项就好。
