### ISSUE TITLE
定制研究生模板声明页

### ISSUE THREAD

**Issue by atxy-blip** [nju-lug/NJUThesis#96]
<https://github.com/nju-lug/NJUThesis/discussions/95> 带来了一个新的问题：声明页可能有不同的样式，而且位置也不固定，有可能在封面后，也有可能在文档结尾（研究生院啊研究生院）。

目前模板是通过 `decl-page` 选项在 `\maketitle` 后自动生成一个声明。如果需要额外选择不同样式，或许删掉这个选项，然后用 `\makedecl` 命令替代比较好？这样用户就能手动选择哪个声明放在哪里了，也可以加上扫描件。可能的用法如：

```TeX
\makedecl 
\makedecl[orig]
\makedecl[scanned={foo.pdf}]
```

-----

如果这个选项改了，那干脆生成国家图书馆封面的 `nlcover` 选项也删了，只用 `\maketitle*` 的可选星号来实现？

**Comment by dreistein543** [comment]
弃疗来看，最简单的方式就是直接额外生成一页/两页（根据不同需求），在打印完成后，装订之前手动调整位置（因为声明页不与其他页粘连，也不涉及页眉和页码）

**Comment by atxy-blip** [comment]
> 装订之前手动调整位置

未免过于弃疗了。这些边角细节问题肯定是要由模板包办的，用户只要专心码字就可以了。

还有另一种办法，目前我也打算这么做：v0.16.0 也就是当前的开发版提供了配置文件选项，模板本身只提供一个通用的框架，然后在仓库里用 `configs/` 提供特定的配置，供有需要的同学单独载入。

**Comment by atxy-blip** [comment]
扫描件大概是个小众需求，所以仅仅增加了如何使用 `pdfpages` 宏包插入外部 PDF 文件的方法。
