### ISSUE TITLE
[Bug]: 英文摘要首页 THESIS 分行不正确

### ISSUE THREAD

**Issue by vill-jiang** [nju-lug/NJUThesis#98]
### 先决条件

- [X] 我已尝试更新[模板版本](https://github.com/nju-lug/NJUThesis/blob/master/CHANGELOG.md)

- [X] 我已检索[模板手册](http://mirrors.ctan.org/macros/unicodetex/latex/njuthesis/njuthesis.pdf)

- [X] 我已检索[项目 wiki](https://github.com/nju-lug/NJUThesis/wiki)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues) 中提出过。

### 期望的现象

![image](https://user-images.githubusercontent.com/24198247/158048499-9f7d3abf-d20f-4d28-80f9-beab4b67ec1d.png)

### 发生了什么

![image](https://user-images.githubusercontent.com/24198247/158048514-3f3db377-2312-4f4f-93fb-493479d31b52.png)

长标题和长单词在换行时会导致摘要页标题的第二行为空。

### 最小工作示例

```TeX
\njusetup {
    info = {
        title* = { This is My LongLongLong LongLongLong LongLongLong LongLongLong LongLongLong LongLongLong LongLongLong English Title },
    }
}
```

### njuthesis 模板版本

0.15.0

### 模板获取途径

<https://tex.nju.edu.cn>

### 编译引擎

XeLaTeX

### 额外信息

tex.nju.edu.cn 当前默认的模板版本。

**Comment by atxy-blip** [comment]
这未免也太长了……

制作之初以为两行顶天，写法简单了一点。下周有空改改。

**Comment by vill-jiang** [comment]
其实本是两行顶天的：
`title* = { Wordword and Wordwordwordword Wordword Words Wordwordwor Wordwordwordwo in Word Wordod Wordword Wordwords }`
![image](https://user-images.githubusercontent.com/24198247/158049630-b91a8a9b-6360-4e6f-9fff-fcb7ec10257d.png)

看到上面的情况我以为太长了，就缩减了一个 and：
`title* = { Wordword \& Wordwordwordword Wordword Words Wordwordwor Wordwordwordwo in Word Wordod Wordword Wordwords }`
但是分行断词了。
![image](https://user-images.githubusercontent.com/24198247/158049656-5a21ddb9-c7ce-4328-9d39-cb67f255c932.png)

主要是因为有三个长长的单词，比较难缩减词数，就碰到模板天花板了😅。

**Comment by atxy-blip** [comment]
发现这周为了搞中期报告咕了没修（

由于存在这个画到行尾的下划线，我研究一下怎么利用自然的断词算法实现吧，这个问题要拖一拖了 Orz

**Comment by vill-jiang** [comment]
作为权宜之计，我暂时把 source\njuthesis.dtx 中 第 4983-4986 行中的 { 1 } { 40 }  和  { 41 } { -1 } 修改这 40 个字符的换行位置而暂时避免单词破碎。
```
    \@@_ulined_center_box:nn { \l_@@_tmp_dim }
      { \tl_range:Nnn \l_@@_info_title_en_tl { 1 } { 40 } } \\
    \@@_uline:n { \textwidth } \@@_qquad:
    \tl_range:Nnn \l_@@_info_title_en_tl { 41 } { -1 }
```
幸苦你日后研究一下自然的断词方法啦。👍

**Comment by atxy-blip** [comment]
目前计划套用 <https://tex.stackexchange.com/questions/637861/underline-list-item-to-page-width> 提供的 primitive TeX 写法。
